Update cookie-helper: add samesite [fixes #8670]
mozilla/bedrock pull request #10180
Opened 2021-04-30 13:24 UTC by Abhra303

## Description
This PR will let the cookie-helper lib set the samesite explicitly. Boolean value 'true' and 'false' will be evaluated to 'strict' and 'none' respectively. Also user can set the value of samesite by specifying numbers ( for ex- 1 will be 'strict' and -1 will be 'none' .Besides strings like 'strict', 'lax', 'none' will also work (case-insensitive).  The default value is 'lax'
## Issue / Bugzilla link
#8670

2021-05-11 12:18 UTC, alexgibson requested changes
Thanks for the pull request @Abhra303!

One small performance optimisation and an open question on the supported parameter values, but otherwise this seems to work well when testing locally. 

Let me know if you have any questions, thanks again.

2021-05-12 02:27 UTC, Abhra303 commented on media/js/base/mozilla-cookie-helper.js
> +                return vSamesite.toString().toLowerCase();
Sorry for this. Don't know why this was not in my mind. Fixing it!

2021-05-12 02:46 UTC, Abhra303 commented on media/js/base/mozilla-cookie-helper.js
> +         *  For all other values of vSamesite the samesite value will be 'lax'
@alexgibson  There is no specific reason for this. I was thinking of giving more options to the developers for setting the samesite attribute. 
We can use samesite without integers and booleans .

2021-05-12 05:11 UTC, Abhra303 commented on media/js/base/mozilla-cookie-helper.js
> +         *  For all other values of vSamesite the samesite value will be 'lax'
Should I allow setting the samesite attribute for strings only?

2021-05-12 06:19 UTC, alexgibson commented on media/js/base/mozilla-cookie-helper.js
> +         *  For all other values of vSamesite the samesite value will be 'lax'
I’m all in favour of keeping it simple, strings only makes sense to me 👍

2021-05-12 12:55 UTC, Abhra303 commented
Setting the samesite attribute equal to 'none' requires the cookie to have 'secure' . Else It will give warnings. See - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#samesitenone_requires_secure

2021-05-12 13:47 UTC, alexgibson approved these changes
Looks good to me, thanks for working on this 💯 r+

2021-05-12 13:47 UTC, alexgibson commented on media/js/base/mozilla-cookie-helper.js
> +        // setting the samesite attribute to 'none' requires the cookie to be 'secure'
Nice addition 👍

2021-05-12 13:47 UTC, merged