Update /firefox/new/ images for MR1 [#10184]
mozilla/bedrock pull request #10227
Opened 2021-05-27 18:12 UTC by craigcook

## Description
Updates images on /firefox/new for the MR1 release, behind the switch `firefox-mr1-launch`
Specifically:
- New screenshot in the page hero
- Recolored noodles in the page hero
- Recolored noodles behind the comparison table
- New screenshot in the ad tracker blocking section
- New screenshot in the customize section
- Recolored noodles in the customize section

We can clean up the old assets post-launch.

## Issue / Bugzilla link
#10184 

## Testing
http://localhost:8000/firefox/new/

2021-05-27 18:37 UTC, craigcook commented
Just got a few more, updating the spot illustrations in the features section that have a browser window. DNM until I get them added.

2021-05-27 19:00 UTC, craigcook commented
New feature illustrations added.

2021-05-27 23:19 UTC, stephaniehobson requested changes
The new colours are ✨ The changes are straight forward but I have one code nit and `screen-mr1`, `block-mr1`,`devices-mr1`, and their high res version could do with some optimization.

2021-05-27 23:19 UTC, stephaniehobson commented on bedrock/firefox/templates/firefox/new/desktop/download.html
> +        <div class="c-block-img">
The opening div with class `c-block-img` should be outside the if/else. Or its closing tag should be inside the if/else block. Right now there's two opening tags on one closing tag and it makes me nervous 😬

2021-05-28 00:03 UTC, stephaniehobson approved these changes
R+ 🕴️

2021-05-28 00:03 UTC, merged