Remove outdated whatsnew pages [no bug]
mozilla/bedrock pull request #10258
Opened 2021-06-09 01:04 UTC by craigcook

## Description
Removes templates, assets, and tests for WNPs 79-85, and also removes the experiment bits from WNP88 (none of the variants outperformed the control).

## Testing
Make sure I didn't miss anything or delete anything still in use somewhere.

2021-06-10 17:26 UTC, craigcook commented on bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html
> +              <a class="c-menu-item-link" href="https://blog.mozilla.org/?{{ utm_params }}" data-link-name="Mozilla Blog" data-link-type="nav" data-link-position="topnav" data-link-group="who-we-are"
Just gonna sneak this in...

2021-06-11 12:17 UTC, alexgibson requested changes
Changes look good, nice clean up 💯 

I noticed a couple of stray assets:

- Some images in the media directory? https://github.com/mozilla/bedrock/tree/master/media/img/firefox/whatsnew
- The tests that are being removed can also have their associated page objects cleaned up: https://github.com/mozilla/bedrock/tree/master/tests/pages/firefox/whatsnew

2021-06-11 14:11 UTC, craigcook commented
See, I knew I'd forget something... updated!

2021-06-11 15:26 UTC, craigcook commented
There was a test failure for WNP86 in French. Originally we were serving FR the whatsnew81 template, but since that's being deleted FR was getting the standard account page, which has no S2D widget so the tests failed. We could update the view to show the standard mobile page to FR (instead of account), but I opted to just remove the tests and not do anything special for French. We could also just delete the 86 page entirely, but I figured we should wait until Fx90.

2021-06-11 16:11 UTC, alexgibson approved these changes

2021-06-11 16:11 UTC, merged

2021-06-11 16:12 UTC, craigcook commented
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/319456041