Update Edge information for the browser comparison page
mozilla/bedrock pull request #10312
Opened 2021-07-05 21:32 UTC by ElijahPepe

Per the new Edge, autoplay blocking, an in-browser screenshot, and support for macOS and Linux have all been introduced. Sources:

https://www.microsoftedgeinsider.com/en-us/download?platform=linux-deb
https://techcommunity.microsoft.com/t5/articles/introducing-web-capture-for-microsoft-edge/td-p/1721318
https://www.microsoft.com/en-us/edge
https://www.onmsft.com/how-to/how-to-block-auto-playing-media-in-the-new-microsoft-edge
https://answers.microsoft.com/en-us/microsoftedge/forum/all/how-to-prevent-video-autoplay-in-chromium-edge/7b0bf188-1915-4b61-b186-103fbc6ba556

## Description

## Issue / Bugzilla link

## Testing

2021-07-06 08:29 UTC, alexgibson requested changes
Thanks for the PR to update this! 

Looks like there is also a chart that needs the same updates at http://localhost:8000/en-US/firefox/browsers/compare/edge/

If you have time to update this as well, it would be very much appreciated? 🙂

2021-07-06 16:27 UTC, ElijahPepe commented
Added those changes there.

2021-07-07 08:36 UTC, alexgibson approved these changes

2021-07-07 08:36 UTC, alexgibson commented
Thanks!

2021-07-07 08:36 UTC, merged

2021-07-08 21:06 UTC, yoasif commented
Does beta really count as a Linux release for Edge?

2021-07-08 22:33 UTC, ElijahPepe commented
Really, what the OS availability row appears to count is if it's even available officially for all OSes. What "Beta" seems to be on Edge is just a quicker update time with the downside of containing more bugs that normally would be caught before an official release. A majority of users using Linux probably wouldn't encounter significant issues while using a beta version. The best way to solve this is a notice stating that the Linux version of Edge is in beta, but I don't see much of the need and rush to clarify that over a serious bug or outdated information.