Update deprecated protocol feature components (Issue #10341)
mozilla/bedrock pull request #10348
Opened 2021-07-28 09:43 UTC by maureenlholland

## Description

`firefox/developer` pages use [Protocol's Feature Card component](https://protocol.mozilla.org/patterns/molecules/feature-card.html), which will be deprecated. We want to replace this component with [Split](https://protocol.mozilla.org/patterns/organisms/split.html) where possible

## Issue / Bugzilla link
https://github.com/mozilla/bedrock/issues/10341

## Testing
TBA

2021-07-28 11:53 UTC, maureenlholland commented on bedrock/firefox/templates/firefox/developer/includes/performance.html
> -<section class="mzp-l-content t-performance" id="nextgen">
note: may need to restore id

2021-07-29 11:42 UTC, maureenlholland commented on bedrock/firefox/templates/firefox/developer/includes/performance.html
> -<section class="mzp-l-content t-performance" id="nextgen">
ID restored

2021-07-30 07:04 UTC, craigcook approved these changes
This looks great, excellent work! A few minor redundancies we could tidy up if you want to, but they're not significant. And it's up to you if you want to add an ID to the Split macro as part of this or in a separate PR.

So an initial r+ and I can review any updates if you make them, but also happy to merge this as-is.

2021-07-30 10:29 UTC, maureenlholland commented on bedrock/firefox/templates/firefox/developer/includes/performance.html
> +<div id="nextgen">
Added! I also saw a `background_class` conditional but think it was meant to be `theme_class`, so made the switch. For some reason, the closing div seemed to be added in any case for split components with theme classes (see https://www.mozilla.org/en-US/about/policy/lean-data/ & http://localhost:8000/en-US/about/policy/lean-data/)

2021-07-30 14:17 UTC, craigcook requested changes
One teeny nitpick to add quotes, then I think we're good to go.

2021-07-30 14:17 UTC, craigcook commented on bedrock/base/templates/macros-protocol.html
> +<section {% if id %} id={{ id }} {% endif %} class="mzp-c-split{% if block_class %} {{ block_class }}{% endif %}">
This should include quotes around the value:
```suggestion
<section {% if id %}id="{{ id }}"{% endif %} class="mzp-c-split{% if block_class %} {{ block_class }}{% endif %}">
```

2021-07-30 14:17 UTC, craigcook commented on bedrock/base/templates/macros-protocol.html
> +  {% if theme_class %}
Oops! Good catch.

2021-07-30 18:22 UTC, craigcook approved these changes

2021-07-30 18:24 UTC, merged