Updating Feature Card components with Split
mozilla/bedrock pull request #10372
Opened 2021-08-05 22:50 UTC by reemhamz

## Description
Replacing the soon-to-be deprecated [Feature Card components](https://protocol.mozilla.org/patterns/molecules/feature-card.html) in some pages with the new [Split component](https://protocol.mozilla.org/patterns/organisms/split.html). 
## Issue / Bugzilla link
#10341 
## Testing
http://localhost:8000/en-US/firefox/sync/
## Notes
In http://localhost:8000/en-US/firefox/sync/, at `350px` mobile view, the Split media image starts to break, and the ordered list stops centering.

2021-08-13 04:22 UTC, craigcook requested changes
Looks good, just some minor tweaks and cleanup. Nice work!

2021-08-13 15:11 UTC, reemhamz commented on bedrock/foundation/templates/foundation/annualreport/2019/index.html
> +    <a href="#" class="mzp-c-button mzp-t-secondary mzp-t-lg">
omg... why did i change the button to an anchor tag? i have no clue, my bad thanks for catching that 🥲 awkward.

2021-08-13 15:19 UTC, reemhamz commented on bedrock/foundation/templates/foundation/annualreport/2019/index.html
> +    <a href="#" class="mzp-c-button mzp-t-secondary mzp-t-lg">
Ah, I must have copied it straight from the Protocol docs. I seen now

2021-08-13 15:28 UTC, reemhamz commented on media/css/foundation/annual-report-2019.scss
> +        text-align: center;
Ah, when I was using the anchor tag instead of a button, the text wasn't centered on mobile. No need for that now.

2021-08-13 20:07 UTC, craigcook requested changes
Just a few last bits and we'll be good to go.

2021-08-13 20:07 UTC, craigcook commented on bedrock/firefox/templates/firefox/sync.html
> +  Firefox Browser
Just realizing, this should probably be a string and added to the Fluent file. Sorry I missed that.
You can add it to `/l10n/en/firefox/sync.ftl` and use the `{ -brand-firefox-browser }` placeable.

2021-08-13 20:07 UTC, craigcook commented on bedrock/firefox/templates/firefox/sync.html
> +<h2>{{ ftl('firefox-sync-start-syncing-in') }}</h2>
Nit: indentation

2021-08-13 20:07 UTC, craigcook commented on bedrock/foundation/templates/foundation/annualreport/2019/index.html
> +    <button type=button class="mzp-c-button mzp-t-secondary">
Nit: attribute values in HTML should be double-quoted
```suggestion
    <button type="button" class="mzp-c-button mzp-t-secondary">
```
Same on the other buttons, too.

2021-08-13 21:07 UTC, craigcook commented on l10n/en/firefox/sync.ftl
> +firefox-sync-firefox = { -brand-name-firefox } browser
There's a `-brand-name-firefox-browser` you could use here, or it could just be "Firefox"

2021-08-17 18:49 UTC, craigcook approved these changes

2021-08-17 18:51 UTC, merged