Add new evergreen mobile product pages [fix #10182]
mozilla/bedrock pull request #10425
Opened 2021-09-07 21:38 UTC by craigcook

## Description
Adds new mobile product pages, replacing the old unified mobile page. We now have separate pages for Android and iOS, as well as a new page for Focus, and a new mobile browser comparison page.

The Focus page has a new native-style mobile banner for Focus, and you'll need to use an iOS or Android device to see it.

The old unified page is being kept temporarily as a fallback for the main mobile index page until sufficient locales can update.

## Issue / Bugzilla link
#10182 

## Testing
http://localhost:8000/firefox/browsers/mobile/
http://localhost:8000/firefox/browsers/mobile/android/
http://localhost:8000/firefox/browsers/mobile/ios/
http://localhost:8000/firefox/browsers/mobile/focus/
http://localhost:8000/firefox/browsers/mobile/compare/

2021-09-09 15:58 UTC, alexgibson requested changes
I'll definitely need a second pass at this one I think, but I took a first run through and left some comments. All the pages look great!

The only common design issue I noticed was the main page headlines bleed over the coloured background gradients at mid-viewport sizes.

<img src="https://user-images.githubusercontent.com/400117/132720514-d4787707-7d9c-4bd3-9fa0-2d6a337c42d9.png" alt="Screenshot 2021-09-09 at 16-26-36 Firefox Browser Android" width="400">

2021-09-09 15:58 UTC, alexgibson commented on bedrock/exp/urls.py
> -    page('firefox/mobile', 'exp/firefox/mobile.html', ftl_files=['firefox/mobile']),
Is it worth adding a redirect for this URL, incase there are external links to it?

2021-09-09 15:58 UTC, alexgibson commented on bedrock/firefox/templates/firefox/browsers/mobile/compare.html
> +  {{ js_bundle('firefox_compare_mobile') }}
The JS bundle here is loading the send-to-device form but not initialising it, so the form posts to a blank page.

2021-09-09 15:58 UTC, alexgibson commented on bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-focus.html
> +  {% else %}
Would this conditional ever be seen? Seems like s2d is available for DE?

2021-09-09 15:58 UTC, alexgibson commented on bedrock/firefox/templates/firefox/faq.html
> +              url2=url('firefox.new.protocol.download_windows'),
This page is throwing a 500 error for me with `Reverse for 'firefox.new.protocol.download_windows' not found.`

2021-09-09 15:58 UTC, alexgibson commented on l10n/en/firefox/browsers/mobile/compare.ftl
> +mobile-compare-5-of-the-best = 5 of the best mobile Browsers in direct comparison
Should `Browsers` here be lower case?
```suggestion
mobile-compare-5-of-the-best = 5 of the best mobile browsers in direct comparison
```

2021-09-09 15:58 UTC, alexgibson commented on l10n/en/firefox/browsers/mobile/compare.ftl
> +
Nit: remove blank lines?

2021-09-09 15:58 UTC, alexgibson commented on media/css/firefox/browsers/mobile.scss
> +// }
Is this needed still?

2021-09-09 15:58 UTC, alexgibson commented on media/js/firefox/browsers/mobile.js
> +        // formSecondary.init();
Is this needed?

2021-09-09 17:59 UTC, craigcook commented
Rebased and updated to address most of the comments.

But it seems the `fx-focus` message set no longer exists in Basket, so marking this as Do Not Merge until we can get that sorted. If we can dig up the old translated emails we can set up a new message set for Focus but if we have to start fresh with a new email we might have to think of something else. Maybe we could launch the Focus page with just the QR code.

2021-09-14 21:30 UTC, craigcook commented
The email folks are going to rework the email for Focus and rather than wait any longer we've opted to move ahead with just the QR code on the Focus page, and we can add the widget for Focus when it's ready.

2021-09-15 08:50 UTC, alexgibson approved these changes
r+ ☎️

2021-09-15 08:50 UTC, merged