fixed clipboard issue
mozilla/bedrock pull request #10509
Opened 2021-09-24 02:56 UTC by Ayushsunny

## Description

Fixed all clipboard code snippets 

## Issue / Bugzilla link

#10453

2021-09-24 02:58 UTC, Ayushsunny commented
Hello @maureenlholland  , @reemhamz 

Could you please review this PR.
And sorry for the late.

2021-09-27 13:16 UTC, maureenlholland requested changes
@Ayushsunny Fantastic work! There are a lot of pages to check here and they are looking much better with the new code blocks. 

A couple of minor changes and one final code block to separate out, under Fluent: https://bedrock.readthedocs.io/en/latest/l10n.html#active-locales

It would be good to keep the following separate for copy/paste:
```
$ ./manage.py l10n_update
```
```
$ ./manage.py active_locales mozorg/mission
```

Then we can put the following block under the explanation text "You get an alphabetically sorted list..."
```
There are 91 active locales for mozorg/mission.ftl:
- af
- an
- ar
- ast
- az
- be
- bg
- bn
...
```

Hopefully this makes it clear that the long block of locales is an output example, and not something you want to copy/paste.

Let me know if you have any questions. Thanks again for picking this up!

2021-09-27 13:16 UTC, maureenlholland commented on docs/pipeline.rst
> +        $ MOZ_GIT_REMOTE=mozilla bin/tag-release.sh --push
I think we want to keep this command under the `bin/tag-release.sh` command so it's still clear they are equivalent, but in separate code blocks so you can copy one or the other.

2021-09-27 13:16 UTC, maureenlholland commented on docs/install.rst
> +1.Create a virtual env in the folder `venv` ::
```suggestion
1. Create a virtual env in the folder `venv` ::
```

2021-09-27 13:16 UTC, maureenlholland commented on docs/install.rst
> +2.Activate the virtual env. On Windows, run: venv\Scripts\activate.bat ::
```suggestion
2. Activate the virtual env. On Windows, run: venv\Scripts\activate.bat ::    
```

2021-09-27 13:16 UTC, maureenlholland commented on docs/install.rst
> +3.Securely upgrade pip ::
```suggestion
3. Securely upgrade pip ::
```

2021-09-27 13:16 UTC, maureenlholland commented on docs/install.rst
> +4.Installs dependencies ::
```suggestion
4. Installs dependencies ::
```

2021-09-27 18:36 UTC, Ayushsunny commented
Done @maureenlholland

2021-09-28 08:31 UTC, maureenlholland approved these changes

2021-09-28 08:36 UTC, merged