Add fundraising 2021 banner to home page (Fixes #10700)
mozilla/bedrock pull request #10732
Opened 2021-11-11 14:13 UTC by alexgibson

## Description
- Adds 2021 fundraising banner behind the switch `SWITCH_FUNDRAISING_BANNER_EOY2021`.
- Adds secondary "Giving Tuesday" headline behind additional switch `SWITCH_FUNDRAISING_BANNER_GIVING_TUESDAY_2021`.

## Issue / Bugzilla link
#10700

## Testing
TODO

2021-11-15 16:04 UTC, alexgibson commented
This is ready for code review, but still **do not merge** pending stakeholder approval.

2021-11-17 17:47 UTC, craigcook commented
Some locales seem to be pulling the numeric amounts from the params but not the symbol or format so they're defaulting to dollars.

Example, Russian should be  "X ₽" but is showing "$X" :
![image](https://user-images.githubusercontent.com/205591/142249738-935eeaa1-75b4-4b2f-b99e-f0b8db41ae0d.png)

I'm not sure what the cause is, but Russian looks correct in the old banner on dev:
![image](https://user-images.githubusercontent.com/205591/142252047-efa132d4-b8a5-414f-be88-9c97cbf31679.png)

Checking a few other locales, most don't have the banner at all but hi-IN does, and has the same issue both on local with the new banner and dev with the old banner so now I don't even know what to think.
![image](https://user-images.githubusercontent.com/205591/142254205-4519f308-1f36-4948-8166-76ecd0d63d1f.png)
![image](https://user-images.githubusercontent.com/205591/142254306-e71b6a01-a828-4805-93c1-22d49eb9c8d7.png)

2021-11-17 18:01 UTC, alexgibson commented
@craigcook I filed an issue for most of these. `/ru/` has been fixed, so you may need to pull the latest L10n files to see it fixed locally. I'll add `hi-IN` to the issue for Peiying, thanks!

2021-11-17 18:05 UTC, alexgibson commented
Issue is here if that helps: https://github.com/mozilla-l10n/www-l10n/issues/254

2021-11-17 19:19 UTC, craigcook approved these changes
only the teeniest of nitpicks, but I know Peiying would flag it. R+wc! 💰

2021-11-17 19:19 UTC, craigcook commented on l10n/en/banners/fundraising.ftl
> +banner-fundraising-body-v2 = We're proudly nonprofit, working to keep the web healthy. Your contributions help build a safe and open internet.
Should be a curly apostrophe:
```suggestion
banner-fundraising-body-v2 = We’re proudly nonprofit, working to keep the web healthy. Your contributions help build a safe and open internet.
```

2021-11-17 23:21 UTC, craigcook requested changes

2021-11-17 23:21 UTC, craigcook commented on bedrock/base/templates/includes/banners/fundraiser.html
> +        <input type="radio" value="monthly" id="monthly" name="frequency" checked> {{ ftl('banner-fundraising-monthly') }}
[Late-breaking change request](https://github.com/mozilla/bedrock/issues/10700#issuecomment-972258794) to set the default back to One-time

2021-11-18 09:33 UTC, alexgibson commented
Thanks @craigcook updated. Looks like Peiying has fixed the currency L10n bugs as well so I think we're all set here. Going to merge as soon as Circle is happy 👍

2021-11-18 09:46 UTC, alexgibson commented
@craigcook ah, looks like I still need you to approve the last change so I'll leave merging to you. Thanks

2021-11-18 15:34 UTC, craigcook approved these changes

2021-11-18 15:35 UTC, merged