PR Fixes for Pocket Pages
mozilla/bedrock pull request #10832
Opened 2021-11-26 20:17 UTC by reemhamz

## Description
Working on the PR comments left here: https://github.com/mozilla/bedrock/pull/10645 to be added onto https://github.com/mozilla/bedrock/pull/10828. Unfortunately the former got botched I'm working on fixing things up in the latter.

## Issue / Bugzilla link
Original PR holding PR comments: https://github.com/mozilla/bedrock/pull/10645

## Testing

2021-11-29 09:05 UTC, alexgibson requested changes

2021-11-29 09:05 UTC, alexgibson commented on bedrock/externalpages/templates/externalpages/pocket/base.html
> +       <link rel="shortcut icon" href="{% block page_ios_icon %}{{ static('img/favicons/mozilla/apple-touch-icon.png') }}{% endblock %}">
I think can be simplified to:

```jinja
<link rel="icon" type="image/png" sizes="196x196" href="{% block page_favicon_large %}{{ static('img/favicons/pocket/favicon-196x196.png') }}{% endblock %}">
<link rel="shortcut icon" href="{% block page_favicon %}{{ static('img/favicons/pocket/favicon.ico') }}{% endblock %}">
```

2021-11-29 09:05 UTC, alexgibson commented on media/css/externalpages/pocket/components/_platform-footer.scss
> +                    &:hover {
Nit: include `active` and `focus` here too?

2021-11-29 09:05 UTC, alexgibson commented on requirements/dev.txt
> +coverage==6.1.2 \
This doesn't seem related to this PR, so I'd suggest reverting this file to whatever is in the master branch here.

2021-11-29 21:05 UTC, reemhamz commented on media/css/externalpages/pocket/components/_footer.scss
> +$pocket-image-path: '/media/img/externalpages/pocket';
I had to use two different image paths, so I named the one holding pocket paths $pocket-image-path. However, in other files, we do have $image-path holding the pocket paths.

2021-11-30 09:40 UTC, alexgibson approved these changes

2021-11-30 09:40 UTC, merged