WNP 98 for DE/FR (Fixes #11211)
mozilla/bedrock pull request #11248
Opened 2022-02-24 09:34 UTC by alexgibson

## Description
Adds a WNP for Firefox 98 in German and French.

## Issue / Bugzilla link
#11211

## Testing
- http://localhost:8000/de/firefox/98.0/whatsnew/
- http://localhost:8000/fr/firefox/98.0/whatsnew/

2022-02-25 15:34 UTC, maureenlholland requested changes
One minor cleanup request, otherwise this all looks great!

2022-02-25 15:34 UTC, maureenlholland commented on bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-de.html
> +  {{ css_bundle('protocol-split') }}
lovely to see these in use on new code already 🎉

2022-02-25 15:34 UTC, maureenlholland commented on media/css/firefox/whatsnew/whatsnew-98-mobile-eu.scss
> +    .send-to-device-input {
suggestion: remove unused rule (qr codes only on these pages, no input)

2022-02-25 16:26 UTC, alexgibson commented
@maureenlholland thanks for the review, updated

2022-02-28 10:23 UTC, maureenlholland approved these changes
r+ 👍

2022-02-28 10:29 UTC, merged