Fully remove old l10n uses and machinery
mozilla/bedrock pull request #11461
Opened 2022-04-06 19:55 UTC by robhudson

## Description

This work is slowly updating templates to remove uses of the old l10n machinery.

- [x] Remove all uses of `_(...)` and `_lazy(...)`
- [ ] Remove all uses of `{% trans %}` tags
- [ ] Remove old l10n machinery

## Issue / Bugzilla link

## Testing

2022-04-11 15:58 UTC, alexgibson requested changes
This is a great legacy of tech debt payoff, nice job! 💯 

This is a pretty huge set of changes, but I took a pass through the most high visibility pages and spotted a few errors / fixups, but mostly everything is looking a-ok 👍 

A couple of re-occuring gotchas to look out for:

- Strings defined as veriables using `set` might need escaping if the include HTML markup.
- Same for strings passed as variables to Jinja macros / helpers.

2022-04-11 15:58 UTC, alexgibson commented on bedrock/firefox/templates/firefox/testflight.html
> +  title='Help shape the future <br>of Firefox for iOS',
![image](https://user-images.githubusercontent.com/400117/162768299-90121a71-a076-4806-991c-bbecf7fbbeca.png)

2022-04-11 23:47 UTC, robhudson commented on bedrock/settings/base.py
> +USE_I18N = False
Yes, the Django i18n machinery is the l10n code that this removes. Django doesn't have integration with Fluent so we can safely disable this.

2022-04-12 00:08 UTC, robhudson commented
I found all the cases where `{% set ...` had HTML tags. I will do another pass looking for calls to macros in the morning. I appreciate the catch on those.

2022-04-14 13:32 UTC, alexgibson approved these changes
I took another pass and all of the updates look good. I didn't spot any other occurences of formatting / escaping errors. If there are some, they are likely in rogue / minor pages and can be fixed easily enough in a followup.

Would begood to make sure we get a passing integration test run before merging just to be extra safe.

Nice work!

2022-04-14 15:37 UTC, pmac approved these changes
This was a lot bigger than I imagined it would be. Very nice work! Thanks 🥇

2022-04-14 22:55 UTC, merged