fix bug 11476 - Adds css selector for hidden attribute
mozilla/bedrock pull request #11599
Opened 2022-05-10 02:34 UTC by msolorio

## One-line summary

This changeset adds a CSS selector for the hidden attribute in order to provide backwards compatibility for old browsers like IE10. Old browsers were not registering the hidden attribute to hide elements.

## Significant changes and points to review

- `./media/css/protocol/common-old-ie.scss` seemed like a better place for this change, however, it didn't seem to be loading on every page. I might be doing something wrong here.

- I attempted to push up a demo branch to one of the on-demand demos for manual testing in IE, however, was denied permissions. This might be user error here as well. https://bedrock.readthedocs.io/en/latest/contribute.html#server-architecture

- Currently looking into another option to test locally.

## Issue / Bugzilla link

https://github.com/mozilla/bedrock/issues/11476

## Screenshots

(If the changeset updates the UI, please include screenshots so reviewers know what to look for when testing)

## Checklist

If relevant:

- [ ] Tests added
- [ ] Feature flags added to www-config
- [ ] New secrets added to the secrets repository
- [ ] If new dependencies are added, I've checked their license is appropriate

2022-05-11 18:09 UTC, nathan-barrett requested changes
Nice work @msolorio! Thank you for picking this up. 

This same rule should also be added to the file `media/css/protocol/protocol-firefox.scss` since some parts of mozilla.org are served `protocol-mozilla` and others are served `protocol-firefox` depending on what theme they have picked.

As for `common-old-ie` not loading on everypage it will only load on IE 9 and older - so to support IE10+ the location you picked would actually be the better one.

2022-05-11 18:24 UTC, alexgibson commented
We should probably apply this to `common-old-ie` as well, so that IE 9 will hide the elements where this appears.

2022-05-11 21:46 UTC, craigcook commented
Related, I've filed https://github.com/mozilla/protocol/issues/783 to add this to our design system.

2022-05-12 03:44 UTC, msolorio commented
@nathan-barrett @alexgibson Absolutely, I went ahead and added to those 2 files.

2022-05-16 14:31 UTC, alexgibson commented
@nathan-barrett looks like this needs a thumbs up from you as well before we can merge

2022-05-16 16:02 UTC, nathan-barrett approved these changes
awesome, nice work @msolorio 👍🏻

2022-05-16 16:06 UTC, merged

2022-05-17 15:57 UTC, msolorio commented
Thank you, looking forward to doing more of this.