Refactor payouts table for web bug bounty program
mozilla/bedrock pull request #12097
Opened 2022-09-05 14:31 UTC by fkiriakos07

## One-line summary

This changeset refactors the payouts table for the web bug bounty program in order to simplify bounty decisions and make them more consistent.

## Significant changes and points to review

- Specify payouts based on vulnerability severity rating instead of vulnerability class
- use payout ranges instead of specific amount
- add a table to define each severity rating and give examples

## Screenshots

![Screenshot 2022-09-05 at 16 22 59](https://user-images.githubusercontent.com/95376064/188471975-73bc5986-d6ae-43cb-b5e8-a05f6dfbbd16.png)

![Screenshot 2022-09-05 at 16 22 41](https://user-images.githubusercontent.com/95376064/188472106-c8d9f17c-3de7-45e3-aaf1-32b1168c49a7.png)

2022-09-26 21:49 UTC, gene1wood approved these changes

2022-10-10 15:42 UTC, fkiriakos07 commented
@dveditz I removed the confusing screenshot, and the bounty ranges are listed here: https://docs.google.com/document/d/1uTSekST5nOuwo6EKDFhDy_OORH1Cdh1msCLDe_-m4LQ/edit

2022-10-10 16:25 UTC, craigcook commented
Let us know when this is ready.

2022-10-11 14:23 UTC, dveditz approved these changes
lgtm +1

2022-10-11 14:31 UTC, fkiriakos07 commented
Hello @craigcook this is ready for your review, thank you

2022-10-12 22:38 UTC, craigcook requested changes

2022-10-12 22:38 UTC, craigcook commented on bedrock/security/templates/security/web-bug-bounty.html
> +          </p>
Nit: this closing `</p>` tag should go before the list. The same for the other three below.

2022-10-13 11:45 UTC, fkiriakos07 commented on bedrock/security/templates/security/web-bug-bounty.html
> +          </p>
done, thanks

2022-10-19 21:22 UTC, craigcook approved these changes

2022-10-19 21:34 UTC, merged