Refresh the commit access policy DOC
mozilla/bedrock pull request #12113
Opened 2022-09-09 11:55 UTC by sylvestre

Just refreshing a bit the content
cc @globau

2022-09-09 12:09 UTC, stevejalim approved these changes
LGTM @sylvestre - shall I merge this?

2022-09-09 12:11 UTC, sylvestre commented
@stevejalim I would like @globau to double check if you don't mind :)

2022-09-12 06:14 UTC, globau requested changes

2022-09-12 06:14 UTC, globau commented on bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
>  <p>People with this access may not actually be working on Firefox, Firefox for Android or Thunderbird, but their ability to affect them means that the level of trust and familarity required for acces
As you changed `Firefox for Android` to `GeckoView` in the previous point, the same replacement should happen here.

2022-09-12 06:14 UTC, globau commented on bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
> +<p>With this level (scm_level_3), the developer can use <a href="https://moz-conduit.readthedocs.io/en/latest/lando-user.html">lando</a> to land code.</p>
`lando` → `Lando`

2022-11-08 15:29 UTC, stevejalim commented on bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
>  <p>People with this access may not actually be working on Firefox, Firefox for Android or Thunderbird, but their ability to affect them means that the level of trust and familarity required for acces
```suggestion
<p>People with this access may not actually be working on Firefox, GeckoView or Thunderbird, but their ability to affect them means that the level of trust and familarity required for access are higher.</p>
```

2022-11-08 15:29 UTC, stevejalim commented on bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
> +<p>With this level (scm_level_3), the developer can use <a href="https://moz-conduit.readthedocs.io/en/latest/lando-user.html">lando</a> to land code.</p>
```suggestion
<p>With this level (scm_level_3), the developer can use <a href="https://moz-conduit.readthedocs.io/en/latest/lando-user.html">Lando</a> to land code.</p>
```

2022-11-08 15:30 UTC, stevejalim commented
@sylvestre @globau I've amended this PR based on the comments from @globau

Shall I merge this to `main` now, or does it need further review?

2022-11-08 15:31 UTC, globau approved these changes
lgtm

2022-11-09 11:41 UTC, merged