Remove closed offices from Careers page (closes #12270)
mozilla/bedrock pull request #12273
Opened 2022-10-20 21:43 UTC by reemhamz

## One-line summary
Removing closed office information from Careers pages. 
Primarily removed mentions of the Portland office, as well as the count of offices within the Positions pages

## Issue / Bugzilla link
https://github.com/mozilla/bedrock/issues/12270

To test this work:

- [ ] http://localhost:8000/en-US/contact/spaces/ (removed Portland office from sidebar)
- [ ] http://localhost:8000/en-US/careers/ (removed Portland office from 'A global view' section)
- [ ] http://localhost:8000/en-US/careers/position/gh/3920659/ (removed old office locations and updated the math under 'Our impact is global' headline)

2022-10-20 22:00 UTC, craigcook requested changes
LGTM, just one suggestion. 

And I see "Portland Office" in the Locations dropdown on the job listings page but I think that needs to be removed in GlassDoor, I don't think it lives in bedrock anywhere that I can find. Not sure who we need to talk to about that.

2022-10-20 22:25 UTC, reemhamz commented on bedrock/mozorg/urls.py
> -    page("contact/spaces/portland/", "mozorg/contact/spaces/portland.html"),
nice catch!

2022-10-21 00:38 UTC, craigcook approved these changes
🏢

2022-10-21 00:38 UTC, merged

2022-10-21 03:41 UTC, craigcook commented
D'oh, I missed this test: https://github.com/mozilla/bedrock/blob/main/tests/functional/test_contact.py#L22 I'll submit a PR to fix it.