update mozilla hubs logo
mozilla/bedrock pull request #12407
Opened 2022-11-23 01:27 UTC by yzAlvin

## One-line summary

Update the hubs logo to the new one linked in the issue.

## Significant changes and points to review

changed the code to match patterns used for the other logos (referencing a separate svg file)

## Issue / Bugzilla link

#12399

## Screenshots

<img width="885" alt="Screen Shot 2022-11-23 at 12 27 24 pm" src="https://user-images.githubusercontent.com/14051545/203452939-46de2b77-52aa-4b2a-a5ac-6dd9dfe91df3.png">

## Checklist

If relevant:

- [ ] Tests added
- [ ] Feature flags added to www-config
- [ ] New secrets added to the secrets repository
- [ ] If new dependencies are added, I've checked their license is appropriate

## Testing

run locally and check icon under `innovation` dropdown

2022-12-01 14:13 UTC, maureenlholland requested changes
Looks great! Thanks for the PR. One tiny nit before approval and merge.

2022-12-07 10:22 UTC, maureenlholland commented on bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
> +                <img class="c-menu-item-icon" src="{{ static('img/nav/icons/icon-mozilla-hubs.svg') }}" alt="" loading="lazy">
@yzAlvin thanks again for the PR, are you available to make this update?

2022-12-09 01:14 UTC, yzAlvin commented on bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
> +                <img class="c-menu-item-icon" src="{{ static('img/nav/icons/icon-mozilla-hubs.svg') }}" alt="" loading="lazy">
hi @maureenlholland sorry for the late reply, have been away from computer for some time, thanks for the comment, have made the change

2022-12-09 07:48 UTC, maureenlholland approved these changes
💯 nice work @yzAlvin !

2022-12-09 07:48 UTC, merged