Code Pocket home page banner - DE
mozilla/bedrock pull request #12645
Opened 2023-01-27 22:42 UTC by nathan-barrett

## One-line summary

Add a Pocket People of Deutschland banner to logged out home page: https://getpocket.com/de/

 Designs: https://www.figma.com/file/kcU3YMlOBwoZOuDz76Gwbv/EU-Pocket-POD?node-id=392%3A193&t=DTCq35WyTOW0hza7-1
 Copy: https://docs.google.com/document/d/1Sf4GNeTdVBoAU8QnmghGzrtRiorQqtWTluhzXliJnqE/edit?usp=sharing

## Issue / Bugzilla link
#12629 

## Screenshots
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/30009669/215219866-4aab80ee-ee75-4ee1-9e56-45bffa22e8db.png">

## Testing

To test this works:
`npm run in-pocket-mode`
https://localhost:8000/de

2023-01-28 01:06 UTC, craigcook requested changes
Looks good, just needs a few fixes. Up to you if you want to try redoing it with a background image, that's more work and an inline image with empty alt is fine too. Nice work! 🐻‍❄️

2023-01-30 18:47 UTC, nathan-barrett commented on bedrock/pocket/templates/pocket/home.html
> +              optional_attributes={ 'class': "c-banner-image"}
I'm not sure, the lazy part of me figures it's OK to stay as is? (Since it's already finished)

2023-01-30 18:59 UTC, craigcook commented on bedrock/pocket/templates/pocket/home.html
> +              optional_attributes={ 'class': "c-banner-image"}
Laziness is its own reward!

2023-01-30 19:03 UTC, craigcook approved these changes

2023-01-30 19:25 UTC, merged