Update Firefox Desktop Attribution docs
mozilla/bedrock pull request #13015
Opened 2023-04-20 13:31 UTC by alexgibson

## One-line summary

Updates Firefox stub attribution documentation to better reflect the state of the current system.

## Issue / Bugzilla link

N/A

## Testing

https://bedrock.readthedocs.io/en/latest/install.html#documentation

2023-05-03 16:26 UTC, craigcook requested changes
Looks good and makes sense. Of course I'm no expert so can't verify accuracy, but I was able to follow the explanation. Just one term I was confused by, and a suggestion for moving the flowchart.

2023-05-03 23:54 UTC, craigcook commented on docs/firefox-desktop-attribution.rst
> +   function`_ collects referral and analytics data about frp, where their visit
I just realized this is probably supposed to be "from" and you were one key to the right 😁

2023-05-04 08:41 UTC, alexgibson commented on docs/firefox-desktop-attribution.rst
> +.. _Application Logic Flow Chart: https://www.figma.com/file/q5mJpicWBpzAYuQ3fV00ix/Firefox-Stub-Attribution-Flow?node-id=0%3A1&t=EFe91WQzQ7cXHSiB-1
Will add a note that this link is mozilla access only. I think that's fine, seeing as this is something mostly for our own team to reference.

2023-05-04 08:49 UTC, alexgibson commented
Thanks @craigcook! Updated

2023-05-04 14:26 UTC, craigcook approved these changes
📜

2023-05-04 14:26 UTC, merged