solved issue  #9832
mozilla/bedrock pull request #13195
Opened 2023-05-26 18:11 UTC by yashkhandelwal123

## One-line summary

This changeset (explain what) in order to (why).

## Significant changes and points to review

(Outline the main things changed, and if there are particular parts that need extra scrutiny.)

## Issue / Bugzilla link

## Screenshots

(If the changeset updates the UI, please include screenshots so reviewers know what to look for when testing)

## Checklist

If relevant:

- [ ] Tests added
- [ ] Feature flags added to www-config
- [ ] New secrets added to the secrets repository
- [ ] If new dependencies are added, I've checked their license is appropriate

## Testing

Demo server URL: (or None)

To test this work:

- [ ]

2023-06-16 09:11 UTC, alexgibson requested changes
Thanks @yashkhandelwal123!

Can we please add this as a new string instead?

2023-06-16 10:28 UTC, yashkhandelwal123 commented on l10n/en/firefox/channel.ftl
> +firefox-channel-beta-is-an-unstable-testing = { -brand-name-beta } is an unstable testing and development platform. By default, { -brand-name-beta } sends data to { -brand-name-mozilla } — and someti
Thank you for your message @alexgibson .I will add the provided information as a new paragraph, separate from the existing content.
If you have any specific details or content that you would like me to include, kindly provide them.

2023-06-16 10:40 UTC, alexgibson commented on l10n/en/firefox/channel.ftl
> +firefox-channel-beta-is-an-unstable-testing = { -brand-name-beta } is an unstable testing and development platform. By default, { -brand-name-beta } sends data to { -brand-name-mozilla } — and someti
Let's go with "Note: Firefox Nightly will update at least once per day."

2023-06-20 10:02 UTC, alexgibson requested changes
Thanks for the update @yashkhandelwal123 - some fixes below.

Please test your changes before submitting them for review. Thanks!

2023-06-20 10:02 UTC, alexgibson commented on bedrock/firefox/templates/firefox/channel/android.html
> +    </p>
This should be in the Firefox Nightly section of the page, not the Firefox Beta section. 

It also throws an error as the syntax is incorrect. Please use the following:

```
{% if ftl_has_messages('firefox-channel-beta-update-one-or-more-times') %}
  <p>
    {{ ftl('firefox-channel-beta-update-one-or-more-times') }}
  </p>
{% endif %}
```

2023-06-20 10:02 UTC, alexgibson commented on bedrock/firefox/templates/firefox/channel/desktop.html
> +    </p>
Same issue as above: in the wrong place, and also throws an error.

2023-07-27 12:26 UTC, alexgibson commented
Closing due to inactivity. If you find time to revisit this, feel free to reopen!

2023-07-27 12:26 UTC, closed without merging