Track Firefox downloads from /thanks in GA4
mozilla/bedrock pull request #13415
Opened 2023-07-17 22:24 UTC by stephaniehobson

## One-line summary

Triggers `product_download` from the /thanks page to record the download in GA4.

## Significant changes and points to review

- convert thanks.js and thanks-direct.js to ES6
- add listener to the direct download link
- trigger product_download event when automatic download triggers

## Issue / Bugzilla link

#13238 

## Testing

TODO

2023-07-20 03:46 UTC, stephaniehobson commented
Needs support for firefox-stub and firefox-msi download URLs.

2023-07-21 09:25 UTC, alexgibson requested changes
Code changes look good, just a few minor nits / suggestions

I do have a larger question though: would it make more sense to add this as a global script that can track downloads on button click, as opposed to when loading the /thanks/ page? I know Adria has talked about wanting to move in this direction for how we measure things.

Right now, this won't capture Firefox downloads for pre-release channels, ESR downloads links (which can now appear on many pages), or from other pages like installer-help where we do offer direct download links.

If there's a chance that this might end up as a global script as you make more progress, might it be worth just making it global now and triggering on button click?

2023-07-21 09:25 UTC, alexgibson commented on media/js/firefox/new/common/thanks-direct.es6.js
> +(function () {
NIt: no need to wrap this in an IIFE, webpack will do it for you

2023-07-21 09:25 UTC, alexgibson commented on media/js/firefox/new/common/thanks-direct.es6.js
> +                    );
I think you can simplify this a bit by using an arrow function

(also make sure to add the `useCapture` param at the end for legacy browser support?):

```suggestion
                    directDownloadLink.addEventListener('click', (event) => {
                        try {
                            TrackProductDownload.handleLink(event);
                        } catch (error) {
                            return;
                        }
                    }, false);
```

2023-07-21 09:25 UTC, alexgibson commented on media/js/firefox/new/common/thanks-init.es6.js
> +(function () {
Nit: No IIFE needed

2023-07-21 09:25 UTC, alexgibson commented on media/js/firefox/new/common/thanks-init.es6.js
> +                directDownloadLink.addEventListener('click', function (event) {
Same as above, simplify to arrow function and add `false` for `useCapture`

2023-07-21 09:39 UTC, alexgibson commented
> I do have a larger question though: would it make more sense to add this as a global script that can track downloads on button click, as opposed to when loading the /thanks/ page? I know Adria has talked about wanting to move in this direction for how we measure things.

> Right now, this won't capture Firefox downloads for pre-release channels, ESR downloads links (which can now appear on many pages), or from other pages like installer-help where we do offer direct download links.

> If there's a chance that this might end up as a global script as you make more progress, might it be worth just making it global now and triggering on button click?

I've given this some further thought, and realized you've probably done this so we can still track downloads that link directly to the /thanks/ page (e.g. from AMO?) With that in mind, I think what you have here makes sense for now.

I do wonder if the script needs to be globally available in the base bundle though, which is what you seem to be moving toward in the adjust PR?

2023-07-21 18:07 UTC, stephaniehobson commented
> I do wonder if the script needs to be globally available in the base bundle though, which is what you seem to be moving toward in the adjust PR?

Yup! I'm just rolling it out in bits to make the reviews easier (though, now I see this makes reviewing the overall approach harder :/ )

> Noticed a possible bug: when I download on windows, release_channel has the value of stub, but when on mac, the value is release?

This should be fixed in the adjust PR.

2023-07-24 14:28 UTC, alexgibson approved these changes
Code changes look good to me r+

As you're now transpiling this code and it's a pretty critical page, I wonder if it's worth pushing this to demo and at least testing that the download still triggers like expected on some older browsers. Thoughts?

Alternatively, you could add your tracking code to the `data` bundle globally now (instead of the next PR that will presumably revert these changes?).

2023-07-24 21:04 UTC, stephaniehobson commented
> Alternatively, you could add your tracking code to the `data` bundle globally now (instead of the next PR that will presumably revert these changes?).

Hm, I didn't consider that I might be able to use TrackProductDownload without importing it 🤔

2023-07-24 21:18 UTC, stephaniehobson commented
Going to combine with #13416.

2023-07-24 21:18 UTC, closed without merging