Fluent string fixes for Relay migration
mozilla/bedrock pull request #13456
Opened 2023-07-26 22:47 UTC by stephaniehobson

https://github.com/mozilla-l10n/www-l10n/pull/343#pullrequestreview-1548350918

2023-07-26 23:30 UTC, bcolsson requested changes

2023-07-26 23:30 UTC, bcolsson commented on l10n/en/products/relay/bundle.ftl
>  bundle-banner-body-3 = { -brand-name-mozilla-vpn } protects you from tracking & surveillance while you’re gaming, online banking, or getting work done. Add it to { -brand-name-firefox-relay } for { $
```suggestion
bundle-banner-body-3-v2 = { -brand-name-mozilla-vpn } protects you from tracking & surveillance while you’re gaming, online banking, or getting work done. Add it to { -brand-name-firefox-relay } for { $savings }% off.
```
We'll want to have the % in our string now.

2023-07-26 23:30 UTC, bcolsson commented on l10n/en/products/relay/matrix.ftl
>  plan-matrix-offer-body = { -brand-name-firefox-relay } protects your identity and your inbox with unique email masks. Add on even more security with { -brand-name-relay } phone masking, and save { $s
```suggestion
plan-matrix-offer-body-v2 = { -brand-name-firefox-relay } protects your identity and your inbox with unique email masks. Add on even more security with { -brand-name-relay } phone masking, and save { $savings }% by adding { -brand-name-vpn } protection.
```

2023-07-26 23:30 UTC, bcolsson commented on l10n/en/products/relay/matrix.ftl
>  plan-matrix-price-vpn-discount-promo = <span>Save { $savings }</span> on regular { -brand-name-vpn } price
```suggestion
plan-matrix-price-vpn-discount-promo-v2 = <span>Save { $savings }%</span> on regular { -brand-name-vpn } price
```

2023-07-27 18:17 UTC, craigcook approved these changes
💾

2023-07-27 18:17 UTC, merged