Make VPN affiliate code re-usable for other products (fix #13575)
mozilla/bedrock pull request #13576
Opened 2023-08-15 21:59 UTC by stephaniehobson

## One-line summary

Make VPN affiliate code re-usable for other products.

## Significant changes and points to review

- moves cookie banner HTML to separate file and makes notification more generic
- re-name and move other associated files to remove VPN references
- rename various variable names to remove VPN references
- add affiliate strings to global FTL files so translations are always available, because this seems like the kind of step that is easy to forget when adding it to a new page.
- update docs

## Issue / Bugzilla link

Fix #13575 
See also #13574

## Testing

http://localhost:8000/fr/products/vpn/pricing/?cjevent=test
`npm run test`

2023-08-16 08:53 UTC, alexgibson requested changes
A couple of minor things, but otherwise this all looks good to me. I'd suggest giving this branch a rebase, as it seems a bit behind (and so you can test it with the latest protocol update?)

r+wc

2023-08-16 08:53 UTC, alexgibson commented on bedrock/settings/base.py
> +    "affiliate.ftl",
Nit: remove filename suffix for consistency?
```suggestion
    "affiliate",
```

2023-08-16 08:53 UTC, alexgibson commented on docs/attribution/0005-affiliate-marketing.rst
> +and the VPN product team's `CJ micro service (CJMS)`_.
Should this be `Security and Privacy team's`?

2023-08-16 08:53 UTC, alexgibson commented on media/static-bundles.json.orig
> -{
I don't see this file in the `main` branch, which is weird. Does this branch need a rebase perhaps?

2023-08-16 08:53 UTC, alexgibson commented on bedrock/base/templates/includes/affiliate-banner.html
> +    {% set attrs = 'href="' ~ url('privacy.notices.websites') ~ '" target="_blank" rel="noopener noreferrer"' %}
This is left over from the existing banner, but we can remove `rel="noopener noreferrer"` for same-site links?

2023-08-16 08:53 UTC, alexgibson commented on bedrock/products/templates/products/vpn/landing-refresh.html
> -    {% include 'products/vpn/includes/cookie-notification.html' %}
Can we remove `products/vpn/includes/cookie-notification.html`?

2023-08-16 21:44 UTC, stephaniehobson commented
Rebased and updated.

2023-08-17 09:28 UTC, alexgibson approved these changes
r+wc

2023-08-17 09:28 UTC, alexgibson commented on l10n/en/affiliate.ftl
> +#   $attrs (string) - link to https://www.mozilla.org/en-US/privacy/websites/ with additional attributes.
Nit: remove locale string
```suggestion
#   $attrs (string) - link to https://www.mozilla.org/privacy/websites/ with additional attributes.
```

2023-08-17 09:28 UTC, alexgibson commented on l10n/en/affiliate.ftl
> +### URL: https://www-dev.allizom.org/en-US/products/vpn/pricing/?cjevent=test
NIt remove locale string
```suggestion
### URL: https://www-dev.allizom.org/products/vpn/pricing/?cjevent=test
```

2023-08-17 18:41 UTC, stephaniehobson commented
This is ready to merge but can wait until after All Hands :)

2023-08-28 17:58 UTC, merged