Redirect /firefox/mobile/get-app/ to /firefox/browsers/mobile/get-app/
mozilla/bedrock pull request #13819
Opened 2023-10-24 10:40 UTC by Soumya0803

## One-line summary

The [get-app page](https://www.mozilla.org/en-US/firefox/mobile/get-app/) should live under the same IA as the rest of the Firefox mobile pages and redirect the old URL.

## Significant changes and points to review
 - Page now lives at new URL
 - Redirect is in place for old URL

## Issue / Bugzilla link
#13469 

## Testing
http://localhost:8000/en-US/firefox/browsers/mobile/get-app/ 
http://localhost:8000/en-US/firefox/mobile/get-app/

2023-10-24 11:54 UTC, alexgibson requested changes
Thanks so much for this, great work!

Just one small change and it would be great to add a test for the redirect? r+wc!

2023-10-24 11:54 UTC, alexgibson commented on bedrock/firefox/redirects.py
> +    redirect(r"^firefox/mobile/get-app/", "https://www.mozilla.org/en-US/firefox/browsers/mobile/get-app/"),
```suggestion
    redirect(r"^firefox/mobile/get-app/", "firefox.browsers.mobile.get-app"),
```

2023-10-24 11:54 UTC, alexgibson commented on bedrock/firefox/redirects.py
> +    redirect(r"^firefox/mobile/get-app/", "https://www.mozilla.org/en-US/firefox/browsers/mobile/get-app/"),
Can you please also add a test for this redirect at the bottom of the following file?

https://github.com/mozilla/bedrock/blob/main/tests/redirects/map_globalconf.py

2023-10-24 11:58 UTC, alexgibson commented on bedrock/firefox/urls.py
> +
Oh, it looks like our linter also wants this blank line to be removed. If you do that then the CI check here in the pull request should be happy again.

2023-10-26 18:54 UTC, Soumya0803 commented
Thanks for the review @alexgibson. I have added the requested changes.

2023-10-27 09:01 UTC, alexgibson approved these changes
r+

thanks for contributing! 🎉

2023-10-27 09:02 UTC, merged