Add WNP 121
mozilla/bedrock pull request #13995
Opened 2023-12-08 06:25 UTC by reemhamz

## One-line summary
Adding WNP121. The same template will be used for all locales! And **no variations** ❗ 💯 

We have `en-US`, `en-GB`, `fr`, and `de` translations hard-coded into the template.

- [Copy](https://docs.google.com/document/d/1C-DbPPmue_S7YbWTzETOkk4DfSNM-HFEl9uaDCxhCio/edit)
- [Figma design](https://www.figma.com/file/CZvzHgU9NQMQUm34lomIl5/Firefox-WNP?type=design&node-id=5474%3A1322&mode=design&t=HaDhAXmSSMYm2ylh-1)

## Issue / Bugzilla link
https://app.asana.com/0/home/1202716623574806/1206078601386171

## Testing
http://localhost:8000/en-US/firefox/121.0/whatsnew/

2023-12-13 08:39 UTC, reemhamz commented on bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx120-eu.html
> -      </div>
Realized there was a missing div on this template

2023-12-14 02:04 UTC, craigcook requested changes
Nice work! ✨  Just a few small nits and we can ship this baby before code freeze.

2023-12-14 02:22 UTC, reemhamz commented on bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx121.html
> +    <div class="mzp-l-content mzp-t-content-lg">
Agh, good looking out

2023-12-14 02:27 UTC, reemhamz commented on media/css/firefox/whatsnew/whatsnew-121.scss
> +            }
🦅 👁️

2023-12-14 02:49 UTC, craigcook approved these changes

2023-12-14 02:51 UTC, merged