Add a warning that Nightly will be updated once/twice a day
mozilla/bedrock pull request #14068
Opened 2024-01-10 10:26 UTC by Soumya0803

## One-line summary
Add a warning/notice that Nightly will be updated once/twice a day 

## Issue / Bugzilla link
#9832 

## Testing
http://127.0.0.1:8000/en-GB/firefox/channel/desktop/
http://127.0.0.1:8000/en-GB/firefox/channel/android/

2024-02-07 01:14 UTC, reemhamz requested changes
Thanks for contributing to our codebase! 🎉 
I just have a couple of minor tips and suggestions, but it should be good to go after that.

2024-02-07 01:14 UTC, reemhamz commented on l10n/en/firefox/channel.ftl
> +firefox-channel-nightly-update-one-or-more-times = Note: { -brand-name-firefox-nightly } will update approximately one or two times each day.
There's just a **minor** linting error here on the file, you'll just need to add an extra empty line after this string 👍🏼 (essentially just creating an empty 67th line)

2024-02-07 01:14 UTC, reemhamz commented on l10n/en/firefox/channel.ftl
> +firefox-channel-nightly-update-one-or-more-times = Note: { -brand-name-firefox-nightly } will update approximately one or two times each day.
**Suggestion:** I think changing the string to say the following would roll better
```
Note: { -brand-name-firefox-nightly } will update approximately once or twice a day.
```

2024-02-07 11:03 UTC, Soumya0803 commented
Hi @reemhamz 
Thanks for the review. I have made the requested changes.

2024-02-08 01:17 UTC, reemhamz approved these changes
Nicely done! r+ 💯

2024-02-08 01:17 UTC, merged