Add Monitor plus Banner to homepage
mozilla/bedrock pull request #14143
Opened 2024-01-30 21:42 UTC by nathan-barrett

## One-line summary
Adds Monitor plus banners to homepage - midpage and pencil. This should be live February 6th

## Significant changes and points to review

## Issue / Bugzilla link
#14115 

## Testing
http://localhost:8000/

2024-01-30 21:49 UTC, nathan-barrett commented
This switch PR will need to be pushed on Feb 6th

2024-02-05 21:40 UTC, craigcook requested changes

2024-02-05 21:40 UTC, craigcook commented on bedrock/mozorg/templates/mozorg/home/home-new.html
> +  {# {%- if (LANG == 'de' or LANG.startswith('en-')) and show_pocket_banner -%}
Guessing this comment is an artifact from local testing? I think this needs to be uncommented and the following rule changed to `elif`.

2024-02-05 21:40 UTC, craigcook commented on bedrock/base/templates/includes/banners/pocket-pencil-banner.html
> +<aside class="monitor-plus-banner c-banner hide-from-legacy-ie" id="monitor-banner">
I don't think these name changes should have been committed? Seems like the Monitor banner started life as a copy of the Pocket banner, but the original Pocket banner should be unchanged. These name changes break the Pocket banner styling.

2024-02-05 21:59 UTC, craigcook approved these changes

2024-02-06 02:18 UTC, reemhamz approved these changes
r+ 🍻

2024-02-06 02:50 UTC, merged