Remove `browsers/compare/ie` references
mozilla/bedrock pull request #14167
Opened 2024-02-01 04:07 UTC by reemhamz

## One-line summary
We have outdated information on Internet Explorer on our comparison pages, so it's time to remove the page and references and assets to it.

## Significant changes and points to review
- Removed `compare/ie/index.html` and `compare/ie.ftl` files from codebase
- Removed assets and links leading to the page
- Removed references of IE from the `firefox/browsers/compare/index.html` page

## Issue / Bugzilla link
https://github.com/mozilla/bedrock/issues/14142

## Testing

- [ ] http://localhost:8000/en-US/firefox/browsers/compare/
- [ ] http://localhost:8000/en-US/firefox/browsers/compare/ie
- [ ] http://localhost:8000/en-US/firefox/more

2024-02-01 04:08 UTC, reemhamz commented
Just waiting on an image asset to be updated before it's ready for review

2024-02-01 04:09 UTC, reemhamz commented on l10n/en/firefox/browsers/compare/index.ftl
> -compare-index-looking-for-a-better-fallback = Looking for a better browser? We’ll compare { -brand-name-firefox } with { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-n
I removed some older `-fallback` FTL string IDs that are now being replaced w/ new fallbacks. These were 4+ years old so should be fine to remove

2024-02-07 02:39 UTC, craigcook requested changes
nice work! Just one other card on /more and we can consider IE dead and buried.

2024-02-07 22:47 UTC, reemhamz commented on bedrock/firefox/templates/firefox/more.html
🦅 👁️

2024-02-08 00:37 UTC, craigcook approved these changes

2024-02-08 00:37 UTC, merged

2024-03-27 20:17 UTC, janbrasna commented on bedrock/firefox/templates/firefox/more.html
> -        image=resp_img('img/firefox/more/firefox-ie.jpg', optional_attributes={"loading": "lazy", "class": "mzp-c-card-image"}),
The `'media/img/firefox/more/firefox-ie.jpg'` is still around but it seems it was only ever linked from here. Should it be removed too?

@reemhamz I'm gonna PR pngcrushed versions of some of the changed images here, so I can include the removal of this stray asset with it if it's OK.