fix hackerone program urls
mozilla/bedrock pull request #14391
Opened 2024-04-01 15:18 UTC by fkiriakos07

## One-line summary

We merged our two hackerone programs into one, therefore, we need to remove the old links and use the new one

## Significant changes and points to review

## Issue / Bugzilla link

## Testing

2024-04-03 07:59 UTC, alexgibson requested changes
I spotted one malformed link, and the new URLs all seem to be 404. I don't know the 404 URLs are intended or not and you're waiting on something going live first, but that wasn't really made clear in your pull request.

Either way, this doesn't seem like it's quite ready to merge?

2024-04-03 07:59 UTC, alexgibson commented on bedrock/security/templates/security/bug-bounty/faq-webapp.html
> +        payouts. Please see our <a href="https://hackerone.com/mozilla/policy_scopes">HackerOne program</a>
**question:** this URL gives me a 404, is that expected and you're waiting on a change going live?

2024-04-03 07:59 UTC, alexgibson commented on bedrock/security/templates/security/bug-bounty/faq-webapp.html
> +        page, <a href="https://hackerone.com/mozilla/thanks"></a>.</p>
**issue:** this link is not rendered because the `<a>` contains no link text.

2024-04-03 07:59 UTC, alexgibson commented on bedrock/security/templates/security/bug-bounty/faq-webapp.html
> +        and send you your bounty. Please submit all bugs to our <a href="https://hackerone.com/mozilla">HackerOne program</a>.
**issue:** this link is also 404?

2024-04-03 07:59 UTC, alexgibson commented on bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
> +  <p>All eligible websites and services can be found in the scope tab of the <a href="https://hackerone.com/mozilla/policy_scopes">HackerOne Mozilla program</a> policy page.</p>
**issue:** 404 link?

2024-04-03 07:59 UTC, alexgibson commented on bedrock/security/templates/security/bug-bounty/web-hall-of-fame.html
> +  <p><strong>Our Web bug bounty program has been migrated to HackerOne.</strong> Therefore, we will discontinue adding researchers on this page. Starting from May 2023, researchers will be recognized
**issue:** 404 link?

2024-04-03 07:59 UTC, alexgibson commented on bedrock/security/templates/security/web-bug-bounty.html
> +  <p><strong>We have migrated our web bug bounty program to HackerOne.</strong> Please visit our <a href="https://hackerone.com/mozilla/policy_scopes">HackerOne program policy page </a>to learn more
**issue:** 404 link?

2024-04-03 08:31 UTC, fkiriakos07 commented
Hello @alexgibson , apologies, HackerOne ran into an issue with renaming our program and I forgot to mention that in the PR, I will convert it to draft until the issue is fixed

2024-04-26 13:56 UTC, fkiriakos07 commented
Hello @alexgibson , hackerone still have trouble renaming our program handle, I fixed the links in the PR to the correct one until the program handle issue is fixed. Can you please review?

2024-05-01 15:27 UTC, alexgibson commented
@fkiriakos07 the links still seem to be 404 for me?

2024-05-02 12:02 UTC, janbrasna commented
I see the new program under renamed [hackerone.com/**mozilla**](https://hackerone.com/mozilla/policy_scopes) just fine, it could be the original URLs now showing 404s with the migration complete. This can be superseded by #14536 now.

2024-05-02 12:06 UTC, closed without merging