Update namespace links and redirects
mozilla/bedrock pull request #14412
Opened 2024-04-04 16:50 UTC by janbrasna

## One-line summary

Fixes all dead references from namespaces pages that still need to be kept around to at least point somewhere meaningful.

## Significant changes and points to review

One link has only Archive.org copy surviving today in English, so linked that;)

## Issue / Bugzilla link

#14249

## Testing

http://localhost:8000/projects/xforms/
http://localhost:8000/projects/xbl/
http://localhost:8000/projects/xul/

2024-04-29 12:37 UTC, alexgibson requested changes
Spotted one small issue with a URL that's still 404. Otherwise the changes LGTM, thanks! r+wc

2024-04-29 12:37 UTC, alexgibson commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
**Issue:** when I try `/projects/xforms/2005/type` locally I still get a 404, so I'm not sure this is quite working as intended. Would be nice to add a test for this URL as well?

2024-04-29 12:50 UTC, alexgibson commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
I'm not super clear why this redirect should behave any differently in dev/prod mode but I'll give it a try 👍

2024-04-29 12:54 UTC, janbrasna commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
Oh the redirect is only for `xforms/*` content pages but keeps the `xforms/2005/*` XML namespace view for historic reasons.

(I could only get the XML namespace views working in prod mode, never investigated why's that.)

2024-04-29 13:25 UTC, alexgibson commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
Ok, so the updated redirect seems to be working, but the issue is we're now falling through to a local 404 for `/projects/xforms/2005/type` as opposed to a 404 on MDN.

I believe this is failing because `projects` is not in `SUPPORTED_NONLOCALES` in https://github.com/mozilla/bedrock/blob/main/bedrock/settings/base.py#L433

Honestly, I'm not sure we should really add that back in either. This old XML namespace has not worked for a long time now, I think we're probably OK to forward the URL to https://wiki.mozilla.org/XForms like the other XForms URLs. Does that make sense?

2024-04-29 13:42 UTC, alexgibson commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
@stevejalim it is possible that something here got broken in the recent i18n changes? It's possible that this just hasn't worked for a long time also.

2024-04-29 13:50 UTC, janbrasna commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
I made this to work locally at the time (at this branch point), but maybe it's easier to just not reintroduce the namespace exception from the redirs (now) and I'll investigate later, with the current codebase, whether that makes sense or not and should be better cleaned up completely when it's not working. 

Reviving the XML namespace view (when it's defined, just overridden by the redir) felt like a courtesy fix when at it, but at the same time it was long 301ed away so it's probably not worth the hassle adding (and maintaining) the /projects nonlocale for it.

2024-04-29 14:11 UTC, alexgibson commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
FWIW I tried in both dev and prod modes and got the same 404

2024-04-29 16:58 UTC, janbrasna commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
@alexgibson This is now reverted to its old behaviour and should test for you ok.

Eventually, once you decide whether or not to keep the XML namespace page, I'll either try to make it work with the current codebase in a separate PR later, or get rid of its definitions for good if it's not needed anymore.

2024-04-30 12:27 UTC, alexgibson approved these changes
r+

2024-04-30 12:27 UTC, merged

2024-05-27 17:56 UTC, janbrasna commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
Tried with the current i18n and `/projects/xforms/2005/type` would work by itself as it's in the debug url list being looked up, but it's being redirected to `/en-US/projects/xforms/2005/type/` that's then 404 not found.

However the nonlocales are there in the new i18n:

https://github.com/mozilla/bedrock/blob/ad578eb0b0fbcb53bca65eb325fe347318ed705e/bedrock/mozorg/nonlocale_urls.py#L36

it's just missing in the old settings. I get the two now need to be in sync (right @stevejalim?)

https://github.com/mozilla/bedrock/blob/2bd7bc4741b2116ec64fdd4e906c1c6d47bb59ab/bedrock/settings/base.py#L404

I'm not sure if it's worth adding the `/projects` nonlocale to base settings for just this namespace view to work. I will open an issue to do it the other way around, and remove all the xforms views and special treatment completely, as the namespace URL was 301ed away for a long time anyways. 🤷

2024-05-28 12:37 UTC, janbrasna commented on bedrock/firefox/redirects.py
> +    redirect(r"^projects/xforms(/?\D+)?$", "https://wiki.mozilla.org/XForms"),
👋 @stevejalim Oh sorry I should have been more clear when pinging you — this PR landed working as intended, fixing the URLs — it's the last "improvement" that I'd eventually reverted that spun off this convo: I wanted to revive the namespace view that once was at https://www.mozilla.org/projects/xforms/2005/type (instead of redirecting away to mozwiki general info) — the code's all still there: 

![Screenshot 2024-05-28 at 13 54 55](https://github.com/mozilla/bedrock/assets/1784648/990e8199-282e-48c4-a762-38ad6194b3b5)

(this is served from [this PoC](https://github.com/mozilla/bedrock/compare/main...janbrasna:bedrock:upd/xforms-redir))

The view contents is still defined in `NAMESPACES`:
https://github.com/mozilla/bedrock/blob/b0ab5618131089d8878e07143bf868a0fb50aec4/bedrock/mozorg/views.py#L106-L107
_[main]_

Even the new i18n added a special consideration for it:
https://github.com/mozilla/bedrock/blob/ad578eb0b0fbcb53bca65eb325fe347318ed705e/bedrock/mozorg/nonlocale_urls.py#L36
_[main]_

It would just mean adding the `"projects"` nonlocale URL to the old config to enable this namespace view and stop it from always being locale-prefixed, and it's back. I quickly tested it and it doesn't break any `projects/*` redirects and all `projects/*/foo` 404s still go through the proper i18n if not caught earlier by defined redirections or existing views so I see no change with addition of that nonlocale definition. _(TBH `/projects` was probably ever only used back in the day when the paths were not prefixed, so no content/URL would have ever been prefixed by locale anyways…)_

What Alex raised is the question whether it'd be worth adding the "projects" entry just for this to work: https://github.com/mozilla/bedrock/compare/main...janbrasna:bedrock:upd/xforms-redir — or if not should it go the opposite way: remove all the special treatment and the namespace definition from the codebase, if it's no longer needed and can't be displayed without this change.

When you have a consensus whether to 👍 retrofit or 👎 prune, I'll draft a PR accordingly.