added download cta for french and german pages
mozilla/bedrock pull request #14440
Opened 2024-04-10 07:46 UTC by reemhamz

## One-line summary
Marketing is testing out a campaign and they'd like to see what adding a Firefox download CTA to `/features/private/` page will result in

## Issue / Bugzilla link

https://github.com/mozilla/bedrock/issues/14428

## Testing

- [ ] http://localhost:8000/fr/firefox/features/private/
- [ ] http://localhost:8000/de/firefox/features/private/

2024-04-10 13:03 UTC, alexgibson approved these changes
A couple of small questions/suggestions but otherwise this LGTM r+

One other thing that I guess has already been discussed, but do folks know there's already a Firefox CTA on these pages that gets shown to non-Firefox browsers?

<img width="999" alt="image" src="https://github.com/mozilla/bedrock/assets/400117/3083f169-d178-4fb8-8cc4-3a29ad1e0527">

2024-04-15 01:29 UTC, reemhamz commented on bedrock/firefox/templates/firefox/features/private.html
> +{% if LANG in ['fr', 'de'] %}
The marketing team primarily wants to conduct some A/B tests for French and German locales only

2024-04-15 01:30 UTC, reemhamz commented on media/css/firefox/features/article.scss
> +    justify-content: center;
oop!

2024-04-15 02:06 UTC, reemhamz commented
Leonie confirmed that this is going to be strictly for non-fx users and for the current footer CTA to just be moved above the fold instead of creating an entirely new CTA. I'm just confirming a few things with her before I merge

2024-04-15 09:40 UTC, reemhamz commented
@alexgibson I made some minor changes I think are worth re-reviewing if you have the time :) 

Essentially, the original CTA on the page will move above the fold, and we agreed that the image won't be necessary as it pushes down the CTA even further. So now we have a mid-page CTA above-the-fold and no longer have the footer CTA in the page. I've also only made the CTA to show for non-fx users

2024-04-16 08:21 UTC, alexgibson requested changes
Spotted an issue with the JS. The new CTA looks good though!

2024-04-16 08:21 UTC, alexgibson commented on media/js/firefox/features/features-article.es6.js
> +        midPageCta.parentNode.removeChild(midPageCta);
Issue: this throws an error in Firefox when viewing a locale that doesn't feature a mid page CTA:

```
Uncaught TypeError: can't access property "parentNode", midPageCta is null
```

2024-04-16 08:21 UTC, alexgibson commented on media/js/firefox/features/features-article.es6.js
> +        midPageCta.parentNode.removeChild(midPageCta);
I think you can also simplify all this logic to:

```javascript
const client = Mozilla.Client;
const footerCta = document.querySelector('.c-feature-footer');
const midPageCta = document.querySelector('.c-firefox-midpage-cta');

if (midPageCta && client.isFirefox) {
    midPageCta.parentNode.removeChild(midPageCta);
}

if (footerCta && client.isFirefox) {
    footerCta.parentNode.removeChild(footerCta);
}
```

2024-04-16 10:41 UTC, alexgibson approved these changes
LGTM r+

2024-04-16 10:42 UTC, merged