Fix HackerOne URLs
mozilla/bedrock pull request #14536
Opened 2024-05-01 16:11 UTC by scottmoz

## One-line summary
HackerOne updated the program to a single program under the name `mozilla`. 

## Significant changes and points to review
- Identical to existing [PR from Frida](https://github.com/fkiriakos07/bedrock/tree/fix-hackerone-links)

## Issue / Bugzilla link

## Testing

2024-05-07 13:36 UTC, alexgibson requested changes
The changes here look fine thanks @scottmoz, however I noticed that the "Mozilla Core Services" link at the following URL is now 404. Does it need updating here as well?

http://localhost:8000/en-US/security/web-bug-bounty/

2024-05-07 15:48 UTC, scottmoz commented
Yes, thank you for catching that oversight. I updated the link on that page as well.

2024-05-10 13:45 UTC, alexgibson approved these changes

2024-05-10 13:51 UTC, merged

2024-05-10 19:01 UTC, janbrasna commented
@scottmoz The last commit still keeps two programs - I see this consolidated to just one in the original PR. Is it intentional?

2024-05-10 19:08 UTC, scottmoz commented
It should just be one program. https://hackerone.com/mozilla. The last commit updated the final page `web-bug-bounty` which I overlooked for my initial three changes. Is that what you mean?

2024-05-10 19:30 UTC, janbrasna commented
@scottmoz Yup, see it published here: https://www-dev.allizom.org/en-US/security/web-bug-bounty/ still showing two links. I guess this was supposed to be simplified to a single program too.

2024-05-13 04:11 UTC, fkiriakos07 commented
Hello @janbrasna @alexgibson I fixed the links on the main web bug bounty page in this follow-up PR: https://github.com/mozilla/bedrock/pull/14565. Can you please take a look? many thanks.