More granularly define bounty payouts.
mozilla/bedrock pull request #14594
Opened 2024-05-22 15:45 UTC by tomrittervg

@dveditz @mozfreddyb

2024-05-23 08:36 UTC, mozfreddyb approved these changes

2024-05-23 20:52 UTC, dveditz approved these changes
great changes, thanks!

2024-05-24 08:07 UTC, mozfreddyb commented
@stevejalim FYI

2024-05-24 09:30 UTC, alexgibson requested changes

2024-05-24 09:30 UTC, alexgibson commented on bedrock/security/templates/security/client-bug-bounty.html
> +      <td style="border-top: 0px">
Please remove inline CSS styles from this PR. CSS should be in `.scss` files, external to a page's HTML.

2024-05-31 17:34 UTC, craigcook commented
Closed in favor of https://github.com/mozilla/bedrock/pull/14614. Thanks!

2024-05-31 17:34 UTC, closed without merging