Add Playwright test suite (Fixes #14191)
mozilla/bedrock pull request #14612
Opened 2024-05-29 09:40 UTC by alexgibson

## One-line summary

This PR adds a new suite of integration tests written using https://playwright.dev/. 

## Significant changes and points to review

Right now, this is only run manually and is not (yet) part of our CI deployment process. Once this merges, the next step is to start to run this against a deployment for a while to evaluate it as a potential replacement for our Selenium test suite.

Aims of this new test suite:

1. It's written in JavaScript as opposed to Python, so will hopefully be more familiar for front-end developers to maintain.
2. It's significantly easier to get running locally to run and write tests (everything is managed via an NPM install).
3. It adds more focused, valuable tests (e.g. asserting auto file downloads) compared to the Selenium test suite.

## Issue / Bugzilla link

https://github.com/mozilla/bedrock/issues/14191

## Testing

TODO

2024-06-18 05:48 UTC, reemhamz requested changes
This test suite was a small learning curve compared to Selenium (at least from a front-end perspective), and I appreciate how readable this test suite is! Good job researching for a test suite such as this and implementing it so well 👍🏼 

I read through each file individually and it all seems easier to grasp than what we currently have. 

Now, most of the tests pass, however the only page failing is the `/firefox/all` page, and I think it may have something to do with the [URL updating parameters based on the user's system ](https://github.com/mozilla/bedrock/blob/main/bedrock/firefox/tests/test_helpers.py#L503-L515) (i.e. if you're on desktop, `/#product-desktop-release/` gets added to the URL). 

The main error also showing up mentions that the test timeout is exceeded while waiting on the page to open:

<kbd>![Screenshot 2024-06-18 at 3 46 15 PM](https://github.com/mozilla/bedrock/assets/42309026/2613b34d-ee62-488c-8c03-208da0c6bfff)</kbd>

2024-06-18 12:37 UTC, alexgibson commented
@reemhamz thanks for taking this for a spin, I appreciate it! I'm glad that you could get things up and running ok with only limited instructions and the tests weren't too complicated to follow 😄 

The failing test you mentioned passes OK for me, so my guess here is that the timeout you encountered is because bedrock can get slowed down processing requests for this page, which is currently not very performant. Sometimes we see this same kind of failure in Selenium too in our live tests runs.

With that in mind though, this should improve once https://github.com/mozilla/bedrock/pull/14324 merges. For now, I'll skip these /all/ tests and will refactor once that PR merges 👍

2024-06-19 01:13 UTC, reemhamz commented
Sounds good to me :) I'll approve the PR and I'll leave it to you to merge for when you think it's ready. Great job again!

2024-06-19 02:25 UTC, reemhamz approved these changes
I just noticed some test IDs missing in HTML files, however tests are passing so I don't think it's a blocking issue, but I'd love a bit of an explanation as to why some mof them are missing :O

2024-06-19 09:21 UTC, alexgibson commented on tests/playwright/specs/products/firefox/firefox-developer.spec.js
> +            const footerDownloadOsx = page.getByTestId('footer-download-osx');
The test IDs for download buttons are added automatically in: `bedrock/firefox/templates/firefox/includes/download-button.html`

<img width="533" alt="image" src="https://github.com/mozilla/bedrock/assets/400117/a8415bcb-b9cc-422d-82e8-9ea8b87b36a2">

2024-06-19 09:21 UTC, alexgibson commented on tests/playwright/specs/products/firefox/firefox-installer-help.spec.js
> +                'download-button-desktop-nightly-win'
See reply above :)

2024-06-19 09:22 UTC, merged