Set all VPN pages to use subnav-refresh.html (Fixes #14712)
mozilla/bedrock pull request #14722
Opened 2024-06-21 09:48 UTC by alexgibson

## One-line summary

Removes the old subnav for VPN as it was leading to an inconsistent experience when browsing pages.

## Issue / Bugzilla link

#14712

## Testing

- [ ] http://localhost:8000/en-US/products/vpn/resource-center/
- [ ] http://localhost:8000/en-US/products/vpn/?xv=legacy
- [ ] http://localhost:8000/en-US/products/vpn/pricing/?xv=legacy

2024-06-21 17:30 UTC, janbrasna requested changes
Thank you for this, it was super inconsistent once you also start switching languages (the og subnav had l10n logic on top of it).

I think now with only one nav, these are probably redundant?

2024-06-21 17:30 UTC, janbrasna commented on bedrock/products/templates/products/vpn/landing.html
>  {% endblock %}
As it {% extends "products/vpn/base.html" %}, this block is already there:

https://github.com/mozilla/bedrock/blob/178aa6b762bff6b2741d5acd1e89f5d0e64ff1a7/bedrock/products/templates/products/vpn/base.html#L16-L18

right?

```suggestion
```

2024-06-21 17:30 UTC, janbrasna commented on bedrock/products/templates/products/vpn/pricing.html
>  {% endblock %}
This one also {% extends "products/vpn/base.html" %}, so the same case?

https://github.com/mozilla/bedrock/blob/178aa6b762bff6b2741d5acd1e89f5d0e64ff1a7/bedrock/products/templates/products/vpn/base.html#L16-L18

```suggestion
```

2024-06-21 23:31 UTC, stephaniehobson commented
Does this fix https://github.com/mozilla/bedrock/issues/13065 by any chance?

2024-06-22 00:13 UTC, janbrasna commented
@stephaniehobson I understand the linked issue is mostly misinterpreting the role of subnav (and its utility of not changing around during navigation), and it's easy to understand why: the VPN subnav doesn't make use of the aria-current styling to denote the current page to help understand the local IA: 

https://github.com/mozilla/bedrock/blob/a81d4852e09a474e62b8be86f75316d38fb199f9/media/css/firefox/family/components/_subnav.scss#L139

Maybe if the included subnav gets migrated to the macro (setting these): https://github.com/mozilla/bedrock/blob/a81d4852e09a474e62b8be86f75316d38fb199f9/bedrock/base/templates/macros.html#L196

it might actually resolve said issue?

2024-06-24 11:46 UTC, alexgibson commented
Thanks @janbrasna updated

@stephaniehobson I think https://github.com/mozilla/bedrock/issues/13065 got stuck because everyone has differing opinions about what should be in that nav. This was all pre-refresh though, so maybe we can just close that one out as wontfix?

2024-06-25 22:08 UTC, craigcook approved these changes
🥪

2024-06-25 22:08 UTC, merged