Sub nav updates:
mozilla/bedrock pull request #14751
Opened 2024-06-28 00:35 UTC by wen-2018

1. Update /firefox to have consistent sub navs
2. Remove and re-order links on /firefox/more page

## Significant changes and points to review

## Issue / Bugzilla link

https://github.com/mozilla/bedrock/issues/14718

## Testing

2024-07-02 04:09 UTC, reemhamz requested changes
Good job getting this done, you've done it pretty smoothly!
I just have a couple of questions regarding some files, and I think we should push this to a demo URL so Adria could have a look before we merge. I can take care of that while you're on PTO 👍🏼 I'll approve once some changes are done and Adria gives us the go-ahead

2024-07-02 04:09 UTC, reemhamz commented on l10n/en/firefox/more.ftl
> +we-compare-firefox-v2 = We compare { -brand-name-firefox } with Chrome, Edge, Safari, Opera and Brave to help you make your decision
This string can be removed since it's not being used anywhere

2024-07-02 04:09 UTC, reemhamz commented on bedrock/firefox/templates/firefox/more.html
**Question:** Should we also be adding the subnav to this page?

2024-07-02 18:53 UTC, janbrasna commented on bedrock/firefox/templates/firefox/includes/sub-nav-firefox.html
I think it differs slightly wrt the page title/icon:

![Screenshot 2024-07-02 at 20 50 38](https://github.com/mozilla/bedrock/assets/1784648/6c26b3b2-fe5f-4b17-868f-bbc782dd6a60)

but yea, agree it should be just "Firefox", as the "Mobile" is then the currently selected menu item of the actual subnav on the right, so keeping all the subnavs from just one source file for consistency ❤️

2024-07-02 19:04 UTC, janbrasna commented on bedrock/firefox/templates/firefox/more.html
The subnav is missing in these places: _(where it also often links to… and getting back from there is a pita…)_

- `firefox/features` (and all features subpages too)
- `firefox/browsers/compare` (there the actual comparisons then have their own submenu)
- `firefox/faq` has its own submenu that'd be worth updating with this too
- `firefox/browsers/what-is-a-browser` and `firefox/browsers/browser-history` then kinda reuse the faq submenu but again in a way the IA for browsing back and forth doesn't work, it all leads deeper or away, to isolated silos of pages that don't offer a good hierarchy how to navigate them, and eventually return someplace else. So including these in the subnav overhaul would be awesome 🚀 

Actually the "FAQ" page could itself be a good addition to the subnav, as it's not linked from anywhere visible.

2024-07-02 20:43 UTC, janbrasna commented on bedrock/firefox/templates/firefox/more.html
OTOH there's one tiny issue now introduced with the default `firefox` subnav being also used for `firefox/enterprise` (which previously was on the beta/developer subnav) — the actual "firefox/enterprise" page is not part of this subnav here, therefore you can't get to it via navigation, and can't see the page bolded (aria current page role) when you're there, as it's not in the subnav at all.

I don't think the previous enterprise grouping with beta, dev, mobile beta & TestFlight pages in one subnav was too bad, esp. that the IA in footer also groups ESR with dev and other channels so at least that felt consistent. I never saw the brief so this might have been decided already, but if there's still some undefined leeway in possibility to better group the other channels together, this might be a good opportunity to fix up also their distinct submenu (which, like the issue being tamed here, has the items all over the place when navigating around), so that one could also undergo a little cleanup, making all the items for pages as:
1. https://www.mozilla.org/firefox/enterprise/
1. https://www.mozilla.org/firefox/developer/
1. https://www.mozilla.org/firefox/channel/desktop/
1. https://www.mozilla.org/firefox/channel/android/
1. https://www.mozilla.org/firefox/channel/ios/

one neat consistent submenu for channels.

2024-07-09 04:17 UTC, reemhamz commented on bedrock/firefox/templates/firefox/more.html
Hey @janbrasna -- as usual, your findings are always super impactful to our decision-making‼️
I brought up the fact that the subnav should be on the `firefox/browsers/compare` and `firefox/features` pages and the team agreed and Wen has updated that part. 

However, would you mind explaining why the `firefox/faq` and its connected page in this subnav update? I think it would be worthwhile making new subnavs for these pages rather than use the one that was created in this code update.

Regarding the `firefox/enterprise` page, alongside its old subnav + its connected pages, I brought this up with the SEO manager and will see what they say 👍🏼 as I think it would be worth it to have a discussion/see the reasoning behind these pages.

2024-07-09 15:17 UTC, janbrasna commented on bedrock/firefox/templates/firefox/more.html
Oh I should have separated out what's probably worth taking care of with this changeset and is actionable, from just thinking out loud about all the interconnected content silos with their own local subnavs that I wanted to actually take a look at improving someday, as I regularly get lost in the IA;)

I will explain it better in an issue once I do a little bit of experimenting to see what would help, translating it into some form of drawing mapping out the IA compared to the local navigation content provided. But just to quickly follow up:
- The Enterprise vs. channels is a tricky one as Enterprise is one of the product options for /firefox, but is not in the nav there; it was always grouped in the navigation (=see footer) together with channels. But it's good to have more ways of organising the content to cater to different mental models of where to look for the pages anyways.
- FAQ and the pages its submenu link to have inconsistent subnavs each so trying to navigate from/around FAQ via subnav you're being taken to places quite randomly;) It's now removed from nav so it's slightly less of an issue, but basically why I mentioned it was that its individual submenus, linking between /faq and /browsers/* seo pages could use a similar tidying up like this one day, to a "stable" shared subnav instead of a handful of oneoffs;)

In an ideal world I would love a breadcrumb+subnav combo;) using the left part for hierarchy, and the right corner for topic-level siblings (think "Firefox › Mobile › Focus" left ~  "Desktop Mobile Feature Compare FAQ" right etc.) to explain the local navigation options a bit more.

I'm basically holding off for the potential nav/masthead redesign before looking into more nav issues myself, so that's just what's been on my mind when it came to nav improvements in general…

But none of that is relevant to this change, so sorry for mixing it up all in one place.

2024-07-10 21:28 UTC, reemhamz approved these changes
🍪🥛 r+!

2024-07-10 21:37 UTC, reemhamz commented on bedrock/firefox/templates/firefox/more.html
Spoke to SEO manager, and she mentioned that since the Enterprise page is linked directly in the products page, that it would be worthwhile in the meantime to also have it share the new Firefox subnav. In the future, if we decide to move the Enterprise page from the main products page, then we'll have it share a subnav with the developer page group and tidy them up. Since these subnav changes are incremental and are currently being worked on, we'll hopefully be seeing more changes come soon

2024-07-10 21:37 UTC, merged