CSP: Remove unsafe-eval & unsafe-inline from script-src
mozilla/bedrock pull request #14831
Opened 2024-07-15 23:16 UTC by robhudson

## One-line summary

Remove unsafe-eval & unsafe-inline from script-src

## Issue / Bugzilla link

#14828 

## Testing

I tested locally by clicking around with the console open looking for CSP violations, including the wagtail admin in my checks.

2024-07-16 08:18 UTC, alexgibson commented
Thanks for taking a look at this one @robhudson! It would really be great to make these improvements.

One area that might be worth investigating is GA4. In particular, I see in their [CSP docs](https://developers.google.com/tag-platform/security/guides/csp) there is mention of needing `'unsafe-eval'` if we use any custom JavaScript variables.

I might be mistaken (and maybe @stephaniehobson can confirm?), but we might use a couple still that need removing:

- https://github.com/mozilla/bedrock/issues/13951
- https://github.com/mozilla/bedrock/issues/14054

2024-07-22 23:16 UTC, stephaniehobson commented
Yeah, we are still using those but they can be removed now that GA3 is gone.

2024-07-23 23:24 UTC, robhudson commented
This updates the PR to only remove these from the report-only policy so we can see how it does there and we should get CSP reports in sentry, but it won't break anything since it's not enforced.

2024-11-22 17:49 UTC, janbrasna commented
The GTM changes are published now:
- https://github.com/mozilla/bedrock/issues/15259
- https://github.com/mozilla/bedrock/pull/14910

Does that mean eval() is no longer needed for GA and this can move forward?

2024-11-22 19:03 UTC, stephaniehobson approved these changes
R+ 📜

2024-11-22 19:03 UTC, stephaniehobson commented
@robhudson I've approved this but I'll leave it to you to merge in case it's gotten too stale.

2024-11-22 19:54 UTC, robhudson commented
It's a little stale. I need to refresh my context around it, esp with the webpack bit. I'll be doing more stuff around CSP next week.

2024-11-22 20:05 UTC, janbrasna commented
So that's `unsafe-eval` ✅ — the docs also mention `unsafe-inline` for loading the container, that I feel is worked around here by the bespoke gtm-snippet.js: https://github.com/mozilla/bedrock/blob/9b5f2a33350353a72a215b11b409828baff2cfa0/media/js/base/gtm/gtm-snippet.es6.js#L25-L34

that will hopefully be sufficient (they pass the nonces normally, making it feel like they then drop more inline JS from their code…) so we'll see in the RO violations if there's some spaghetti coming from the loaded sources.

The webpack (re)build performance for different devtool settings for source mapping is described in more depth here:
- https://webpack.js.org/configuration/devtool/
- https://github.com/webpack/webpack/tree/main/examples/source-map#generated-source-maps
(This setting is high fidelity so slow for dev, but at the same time has the most accurate results mapping to the original, so I personally don't mind it too much)

The only question is whether this doesn't wholesale add source maps also to prod outputs?

(FYI I've carefully worked around these lines not to cause any conflicts so this is still good to land as is.)

2024-12-17 17:04 UTC, robhudson commented
Rebased. It sounds like this is good to go for testing in report-only mode. Just wanting to confirm.

2024-12-20 22:40 UTC, janbrasna requested changes
I think the source mapping change may actually impact production outputs, so good the FE codeowners @mozilla/bedrock-codeowners-frontend got pinged for review, to perhaps advise what to do with the devtool in webpack settings:

2025-03-25 21:22 UTC, robhudson commented
This is stale so I'm going to close but leave the issue open.

2025-03-25 21:22 UTC, closed without merging