Also send reports for the enforced CSP
mozilla/bedrock pull request #14911
Opened 2024-07-30 22:02 UTC by robhudson

## One-line summary

Updates our CSP settings so that we send reports to Sentry for both the enforced and report-only policies. We want to know if the enforced policy ever gets triggered so we can fix as soon as possible.

## Testing

Add something like this to your local `.env` file:
```
CSP_REPORT_URI=http://localhost:8000/_csp
```
and verify the headers for `Content-Security-Policy` contain a `report-uri`.

2024-09-06 22:05 UTC, pmac approved these changes

2024-09-10 09:56 UTC, stevejalim requested changes

2024-09-10 09:56 UTC, stevejalim commented on bedrock/settings/__init__.py
> +    "REPORT_PERCENTAGE": config("CSP_REPORT_PERCENTAGE", default="100", parser=int),
Looks like Dev is set to report 5% and stage 2%, but prod has no CSP_REPORT_PERCENTAGE set, which would default to 100% on rollout and could spam Sentry quite hard, maybe?

Might be worth making `default="1"` here, as well as setting a real value for prod in `webservices-infra`

2024-09-17 21:55 UTC, robhudson commented
Updated to default to 1 but also added `CSP_REPORT_PERCENTAGE` to prod in https://github.com/mozilla-it/webservices-infra/pull/2783

2024-09-17 22:20 UTC, stevejalim approved these changes
r+ cheers!

2024-09-17 22:34 UTC, merged

2024-10-13 22:47 UTC, janbrasna reviewed
Is this so that report-only and enforced rules set the same percentage being submitted, and use the same endpoint too? (Do they make sense inside Sentry, i.e. reasonably distinguishable if that came from CSP or CSP-RO?)

Also, float vs. int discrepancy:

2024-10-18 14:54 UTC, robhudson commented on bedrock/settings/__init__.py
> +    "REPORT_PERCENTAGE": config("CSP_REPORT_PERCENTAGE", default="1", parser=int),
Sorry I didn't see your questions. We did find that Sentry doesn't really easily distinguish between enforced vs report-only. They have a "disposition" field but you have to click into the report to see it, it's not distinguishable from the list of issues page unfortunately. These were also adding a lot of noise to our main sentry project so in a later commit I set things up so the report-only violations go to a separate sentry project. (I also noticed the int parser and fixed that there)

2024-11-10 14:24 UTC, janbrasna commented on bedrock/settings/__init__.py
> +    "REPORT_PERCENTAGE": config("CSP_REPORT_PERCENTAGE", default="1", parser=int),
Good we're thinking the same;) Yes, they do collect the disposition, but truth is I wasn't even aware where to look for it (they avoid report-only pretty much in the docs…) — so it's not surprising it's there somewhere in the metadata, but hidden away in a way it's not useful to tell the different sources of reports easily apart. Good that you managed to set up a separate project to receive just the report-only violations (from both prod/stage & dev/demos; or you run report-only just for some of the environments?)