Update newsletter/firefox page (issue #15075)
mozilla/bedrock pull request #15101
Opened 2024-09-10 12:21 UTC by alexgibson

## One-line summary

- Updates the `/newsletter/firefox/` page layout and copy.
- Adds A/B header image test for en-US, de, and fr languages.

## Issue / Bugzilla link

#15075

## Testing

http://localhost:8000/en-US/newsletter/firefox/

2024-09-12 22:09 UTC, stephaniehobson requested changes
We've changed how we record experiment data for GA4, please update to use the new syntax. (also, if you copy and pasted this code from somewhere, we should file an issue to update that too).

Also, there was a problem getting it running locally for me. Not sure if it was me or if you'll see it to if you stop and then re-start your dev server.

Oh... and it needs a rebase ;)

2024-09-13 08:46 UTC, alexgibson commented on bedrock/newsletter/urls.py
> +        VariationTemplateView.as_view(
Ah, looks like the line was removed in https://github.com/mozilla/bedrock/pull/15119/files#diff-05181ef311764e79e4e0f540afdb3d341a0294fed3347b5c4386a810b73c0783

I'll rebase and add it back here, thanks!

2024-09-13 08:58 UTC, alexgibson commented
@stephaniehobson updated thanks

2024-09-13 14:45 UTC, stephaniehobson approved these changes
R+ 🦊

2024-09-13 14:45 UTC, merged