Pin ESR 115 for unsupported operating systems (Fixes #13753)
mozilla/bedrock pull request #15141
Opened 2024-09-13 13:27 UTC by alexgibson

## One-line summary

We're extending support for Firefox ESR 115 since so many outdated Windows / macOS users rely on it. This PR updates the ESR download buttons shown to unsupported website visitors to always return ESR 115. A special alias has been set up in bouncer here called `firefox-esr115-latest-ssl`

Marking this as a P1 since it need to go live before the end of September (when `firefox-esr-latest-ssl` starts resolving to ESR 128)

## Issue / Bugzilla link

#13753

## Testing

Successful test run: https://github.com/mozilla/bedrock/actions/runs/10849536114

You can add a class of `windows fx-unsupported` and `osx fx-unsupported` to the `<html>` element to toggle display of the unsupported messaging.

http://localhost:8000/en-US/firefox/new/

2024-09-16 06:04 UTC, reemhamz requested changes
Good work updating the content for the ticket, however it seems like the website on a windows 32-bit machine doesn't seem to append `fx-unsupported`, and therefore not allowing the ESR message to pop up?

2024-09-16 08:29 UTC, alexgibson commented on bedrock/firefox/templates/firefox/includes/download-unsupported.html
> +      <a class="mzp-c-button mzp-t-product download-link os_win ga-product-download" href="https://download.mozilla.org/?product=firefox-esr115-latest-ssl&os=win&lang={{ LANG }}" data-cta-text="Downl
@reemhamz I think the issue is webpack dev server isn't supported on such old browsers, so to test in browserstack you'll need a production build. I'll push this to demo for you so you can confirm.

2024-09-16 08:31 UTC, alexgibson commented on tests/unit/spec/base/datalayer-productdownload.js
> +    it('should identify release_channel for Firefox ESR 115', function () {
The code in question doesn't seem to test the `os` param, but sure adding another can't hurt 👍

2024-09-16 10:19 UTC, alexgibson commented
@reemhamz I pushed this to a demo server for you to test vs using localhost. It looks OK to me: https://www-demo1.allizom.org/en-US/firefox/new/

2024-09-17 02:18 UTC, reemhamz approved these changes
The demo link worked! You were right about the webpack dev server. r+ 🍰

2024-09-17 02:18 UTC, merged