Refresh: Separate nav and footer styles from protocol base
mozilla/bedrock pull request #15353
Opened 2024-10-21 18:47 UTC by craigcook

## One-line summary
Removes the nav and footer styles from the refreshed Protocol and sets them up in separate bundles. This lets us load only the styling for the appropriate components based on the page language.

This is based on #15312 but is a simplified approach.

## Issue / Bugzilla link
#15120

## Testing
Test with the `M24_WEBSITE_REFRESH` switch both off and on. When off, the site should be all the legacy Mozilla branding. When on, it gets the refreshed branding.

English pages should get the new nav and footer, non-English pages should get the old nav and footer.

2024-10-21 19:05 UTC, wen-2018 requested changes
Great job on simplifying the bundle separation! 

I noticed that the m24 nav and footer have broken styles on the Firefox pages for non English pages. I think the bundle switch logic should be added to:
`bedrock/firefox/templates/firefox/new/basic/base.html`
`bedrock/firefox/templates/firefox/new/desktop/base.html`

2024-10-21 19:05 UTC, wen-2018 commented on media/css/protocol/protocol-mozilla-2024.scss
This part could be moved to the legacy footer stylesheet
```
// temporary logo refresh for old footer
.mzp-c-footer-primary-logo.m24-logo a {
    background-image: url('/media/img/logos/m24/lockup-white.svg');
    height: 27px;
}
```

2024-10-22 15:32 UTC, craigcook commented
Rebased and updated

2024-10-22 17:08 UTC, wen-2018 approved these changes

2024-10-22 17:08 UTC, merged