add Fx 20th NA+EU pages
mozilla/bedrock pull request #15409
Opened 2024-10-30 17:23 UTC by wen-2018

## One-line summary

- [ ] I used an AI to write some of this code.

## Significant changes and points to review

## Issue / Bugzilla link

## Testing

2024-11-01 14:42 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +          <a class="mzp-c-cta-link" href="#" data-cta-text="View blog">
This link needs to be updated when available

2024-11-01 14:42 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +          <a class="mzp-c-cta-link" href="#" data-cta-text="View blog">
This link needs to be updated when available

2024-11-01 14:43 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/video-fanart.html
> +  id='XN3xEfTOW7M',
The video id, title need to be updated when fan art video becomes available

2024-11-01 15:22 UTC, wen-2018 commented on media/img/firefox/whatsnew/whatsnew132/video-high-res.jpg
This file needs to be updated when a high res image is provided

2024-11-04 17:23 UTC, slightlyoffbeat commented
I am sorry that I did not catch this, but it looks like the designs did a lot of borrowing from the WNP, including the header/nav and footer. This should use our standard footer and navigation (not the WNP version). These need to be replaced with our standard footer and navigation

![Screenshot 2024-11-04 at 9 18 49 AM](https://github.com/user-attachments/assets/b31ac0f0-8c76-479f-b8fd-e8cdbb71447b)
![Screenshot 2024-11-04 at 9 19 27 AM](https://github.com/user-attachments/assets/eacee596-756b-4152-bc0c-580c61ed36be)

2024-11-04 18:37 UTC, slightlyoffbeat commented
This appears to have a different behavior for light and dark mode. Lets only have a single design for this.

2024-11-05 10:17 UTC, alexgibson requested changes
This all looks good to me - noticed a couple of tiny things, but otherwise everything else seems to be working as expected. Nice work!

2024-11-06 00:54 UTC, slightlyoffbeat commented
I'm looking at demo, not code, so comments are based on that:
- lets double check background colors and font colors against Figma file. They don't look right
- Lets double check font sizes as well against Figma file.
- can we limit the width of the body copy for the top section?
- this should use mozilla.org standard navigation
- we should remove the section that has "powered by Mozilla", the donate button, and release notes.
- For English -- can we have the two blog sections be equal height, but the two CTAs be equal distance form the bottom of those blocks?

2024-11-06 15:21 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +{% block page_css %}
Social share image has been updated. The page title and desc still have placeholders for now

2024-11-06 16:05 UTC, wen-2018 commented
> * lets double check background colors and font colors against Figma file. They don't look right
- The background color has been updated to match the Figma file to a lighter shade of gray. The only thing that I want to flag is that this is the same shade of gray as the subnav, so now the subnav looks like part of the top section of this page
> * Lets double check font sizes as well against Figma file.
- I have doubled checked all the font sizes and they all match the Figma sizes 👍 
> * can we limit the width of the body copy for the top section?
- I have update the section to limit the width to 80% of its container
> * this should use mozilla.org standard navigation
- This was updated in the code but not reflected on the demo due to an error yesterday, but it's fixed now
> * we should remove the section that has "powered by Mozilla", the donate button, and release notes.
- This is the same demo error that has since been fixed
> * For English -- can we have the two blog sections be equal height, but the two CTAs be equal distance form the bottom of those blocks?
- This has been updated

2024-11-06 16:06 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +  title placeholder
TODO: update title when it becomes available

2024-11-06 16:06 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +  desc placeholder
TODO: update desc when it becomes available

2024-11-06 16:07 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +          <p>It’s official — the built-in PDF editor, popping videos out of your window and tab containers made the list.</p>
This copy might change

2024-11-07 04:15 UTC, slightlyoffbeat commented
### To do:

#### 1. Update meta title, description, image

#### EN:
Title: `Firefox Turns 20 - Celebrate with Us`
Description: `Celebrate 20 years of Firefox — dive into our journey, explore fan creations, meet top contributors and join us as we look forward to an exciting future.`

#### DE: (From Google Translate, may need updating later)
Title: `Firefox wird 20 – Feiern Sie mit uns`
Description: `Feiern Sie 20 Jahre Firefox – tauchen Sie ein in unsere Reise, entdecken Sie die Kreationen unserer Fans, treffen Sie die wichtigsten Mitwirkenden und freuen Sie sich gemeinsam mit uns auf eine spannende Zukunft.`

#### FR: (From Google Translate, may need updating later)
Title: `Firefox fête ses 20 ans – Célébrons-les avec nous`
Description: `Célébrons les 20 ans de Firefox : plongez dans notre aventure, explorez les créations des fans, rencontrez les meilleurs contributeurs et rejoignez-nous alors que nous envisageons un avenir passionnant.`


Image: see [here](https://github.com/mozilla/bedrock/issues/15383#issuecomment-2458478894).

#### 2. New copy on English version.

Because of changes in blog posts, we have new copy and blog post links. 

Please refer to [this document ](https://docs.google.com/document/d/1I2Rar6stuAnFzryvU4XbRVFK0W0LJErPyInrvvtx9Aw/edit?usp=sharing)for the updated copy. @wen-2018 I tagged you on the updated copy. This updated copy also has updated Links (provided in copy document) that should be used, with appropriate UTM parameters. 

#### 3. New image for the fan art section.

The image we had is low res, and we did not secure the rights to use it.

- [Updated mockup is here](https://www.figma.com/design/hd5EzCGnap1aMJ1JfT4lZA/NA-FX-20th-Anniversary?node-id=705-6967&t=8HvtaoPW0IY21To9-1). The mock is the third version with the play button over it.
- The updated asset is exported [here](https://drive.google.com/drive/folders/1q91MFq0C9krtdO9QQ_kKWwojHySFUgc2?usp=drive_link)

Important note: there is a change we do not receive the video in time. If that happens, we should be prepared to ship the section without the play button, or video functionality (it works works without it).

#### 4. Misc
- Lets tighten up space at the top of the page. Feel free to check with Elise or Tess for recommendation.
- There's a line at the bottom of the page that needs to be removed, just above the footer

2024-11-07 16:23 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/video-fanart.html
> +  id='XN3xEfTOW7M',
Removed for now. Will bring back in case video is ready

2024-11-07 16:23 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +{% block page_css %}
Page title and desc are in place for all locales now

2024-11-07 16:23 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +  desc placeholder
Updated

2024-11-07 16:23 UTC, wen-2018 commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +          <p>It’s official — the built-in PDF editor, popping videos out of your window and tab containers made the list.</p>
Updated

2024-11-07 16:39 UTC, alexgibson approved these changes
r+wc

2024-11-07 16:39 UTC, alexgibson commented on bedrock/firefox/templates/firefox/firefox-20th/index.html
> +{% endblock %}
Nit: inline these to remove blank space before/after the content
```suggestion
{% block page_title_full %}{{ page_title }}{% endblock %}
{% block page_desc %}{{ page_desc }}{% endblock %}
{% block page_image %}{{ static('img/firefox/firefox-20th/firefox-20th-social-share.png') }}{% endblock %}
```

2024-11-07 16:39 UTC, alexgibson commented on media/img/firefox/firefox-20th/firefox-20th-social-share.png
**Nit:** I can shave about 30% off this image by running through https://tinypng.com/

2024-11-07 16:52 UTC, wen-2018 commented on media/img/firefox/firefox-20th/firefox-20th-social-share.png
Will run through it again

2024-11-07 16:58 UTC, wen-2018 commented on media/img/firefox/firefox-20th/firefox-20th-social-share.png
Updated now

2024-11-07 17:21 UTC, wen-2018 commented
> #### 1. Update meta title, description, image
- This has been updated
> #### 2. New copy on English version.
- This has been updated
> #### 3. New image for the fan art section.
- I have implemented the section with only the images. I will update it if we receive the video in time
> #### 4. Misc
> * Lets tighten up space at the top of the page. Feel free to check with Elise or Tess for recommendation.
- I have reduced the top section padding.
> * There's a line at the bottom of the page that needs to be removed, just above the footer
- I don't see a line at the moment. I have attached the screenshots of the most recent changed included. Please let me know if a line is still showing for you and I will investigate it further.
![NA](https://github.com/user-attachments/assets/b088a3e2-3f59-4ca8-8bd5-08ba02046c60)
![EU](https://github.com/user-attachments/assets/1d5606df-65ae-4587-bb9c-25f79e4f5f10)

2024-11-07 17:24 UTC, merged

2024-11-07 18:45 UTC, slightlyoffbeat commented
SUMO blog uses dates, and published a day later than planned, which means the URL is 404 now in the English version. it needs to be updated to

`https://blog.mozilla.org/sumo/2024/11/07/celebrating-our-top-contributors-on-firefoxs-20th-anniversary/`