Refresh: Add springboard component (Fix #15305)
mozilla/bedrock pull request #15448
Opened 2024-11-05 17:39 UTC by stephaniehobson

## One-line summary

Add a component to display the list of links to blogs, videos, and podcasts.

## Significant changes and points to review

- It's a table and the summary is a link to the full articles/video/podcast/media.
- Then some Javascript runs to make the entire row clickable and add the full row hover effect.
- I ran this progressive enhancement technique past the accessibility slack channel

## Issue / Bugzilla link

Fix #15305

## Testing

If you want to review the CSS while this is still a draft, giv'er, but I want to improve the Javascript so that's not in need of a review yet.

2024-11-19 15:12 UTC, maureenlholland requested changes
This is looking great cross-browser & screen size 🎉 

My only blocking issue is that it's not clear what's required for the springboard component

Everything else is non-blocking (and praise!)

2024-11-20 18:34 UTC, maureenlholland approved these changes
r+ with comments (docs not truly blocking)

2024-11-20 19:48 UTC, stephaniehobson commented on bedrock/base/templates/macros-m24.html
> +    <!-- <div class="m24-c-springboard-date">{{ date }}</div> -->
It might not be gone forever but it's dead to us. ✅

2024-11-20 19:49 UTC, stephaniehobson commented on bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html
> +    {{ springboard_item(
✅ I don't know how I'd nest the macros but I've addressed this by not using the `item` macro for the headings.

2024-11-20 19:51 UTC, stephaniehobson commented on media/img/home/2024/media/irl-orange-high-res.png
I'm going to leave this as an enhancement. BUT I do need to resize the images now that they're just thumbnails.

2024-11-20 19:55 UTC, stephaniehobson commented on bedrock/base/templates/macros-m24.html
> +    link_url (Required):
Docs updated ✅

2024-11-20 20:55 UTC, stephaniehobson commented on media/css/m24/springboard.scss
> +.m24-t-dark .m24-c-springboard-link:focus-within {
I think this was a vestige of the original dark design. I've simplified it ✅

2024-11-20 20:55 UTC, maureenlholland approved these changes
r+ 

The simplified item-only macro is a lot easier for me to read. Translate notes are great too 📚

2024-11-20 20:56 UTC, stephaniehobson commented on bedrock/base/templates/macros-m24.html
> +    <a href="{{ link_url }}" class="m24-c-springboard-link" {{ link_attributes }}>
I'm going to open a follow-up issue to improve the accessibility. It's... a bit not good.

2024-11-20 21:14 UTC, stephaniehobson commented on media/img/home/2024/media/irl-orange-high-res.png
Images resized ✅

2024-11-20 21:26 UTC, merged