Refresh: optimize images, delete some cruft
mozilla/bedrock pull request #15651
Opened 2024-12-03 23:15 UTC by craigcook

## One-line summary
Just ran images through tinypng. Most had already been optimized but almost everything got another 5-10% savings on a second run without any apparent quality loss.

Ran the icons through SVGO, which only a few really needed but almost all still shaved a few bytes... except a few gained a few bytes from adding line breaks.

Deleted a few old images that have been replaced. I figure we should keep the `todo-*` placeholders for now because they'll be useful on future pages.

## Issue / Bugzilla link
#15416

## Testing
Just make sure I didn't delete anything still in use, and that images haven't degraded in quality.

2024-12-04 05:44 UTC, stephaniehobson requested changes
icon-bell, icon-dollar, icon-glasses, and icon-pencil were in use on the about page. They're larger than 24 and so are okay to have the missing pixel. They don't belong in the m24-small folder though so maybe put them back somewhere else?

2024-12-04 23:52 UTC, stephaniehobson approved these changes
R+

2024-12-04 23:52 UTC, merged

2024-12-05 02:42 UTC, craigcook commented
> icon-bell, icon-dollar, icon-glasses, and icon-pencil were in use on the about page. They're larger than 24 and so are okay to have the missing pixel. They don't belong in the m24-small folder though so maybe put them back somewhere else?

Filed https://github.com/mozilla/bedrock/pull/15684 to restore those icons, now in an `m24-large` folder.

2024-12-09 23:49 UTC, janbrasna commented on media/img/icons/m24-small/protocolwhite.svg
Not sure where the file name comes from… but it's missing a dash — so maybe that might be renamed from `protocolwhite` to `protocol-white` before any widespread use?