Force consistent header height
mozilla/bedrock pull request #15790
Opened 2024-12-24 00:45 UTC by janbrasna

## One-line summary

Refreshed pages have different defaults affecting also nav elements, making shifts in layout visible when navigating to older pages. This sets the base var explicitly to the header components to not inherit any other value.

## Significant changes and points to review

Both the desktop and mobile nav inconsistencies caused by differing line-height as captured in the tracking issue are resolved here by using the "taller" version as that seems to be better aligned in general.

## Issue / Bugzilla link

Fixes #15788

## Testing

/about/ ⇄ /products/

2025-01-06 12:41 UTC, janbrasna commented on media/css/m24/components/navigation-refresh.scss
> +    line-height: var(--body-line-height);
Hmh now with #15803 also affecting footer, and the letterspacing mentioned there too, I'm starting to think whether instead of adding more and more explicit `line-height` and `letter-spacing` values around here for specificity a better approach would be to only apply all of the generic m24-base styles specifically to something like `#outer-wrapper > main` scope, not to interfere with header and footer…?

2025-01-07 17:06 UTC, janbrasna commented
Since I'm not sure which is closer to the original Figma/brief, the tighter line-height or the looser occurrence from the two in https://github.com/mozilla/bedrock/issues/15803#issue-2769494064 I'm not sure which one to effectively use to unify these, if I were to include resolving footer along with the header already in this PR.

Optically the 1.2 looks more harmonic for footer list items. However the original design seemed to prefer the 1.4 for consistency(?)

Currently I think the approach here redefining the components again for specificity is not the right one, and instead only applying the m24-base styles for refreshed pages to the main content might make more sense, but will have bigger change surface to test properly for any unexpected effects (as it also changes specificity when moved around…)

2025-01-08 15:14 UTC, wen-2018 requested changes
I have looked the Figma files. For the new designs, we have 3 line-heights:
- general body texts: 1.2
- headings: 1
- links for the navigation items: 1.1

The pencil banner and footer text both inherit the general body text line height of 1.2. 

1. So we should definitely specifically define the line-height for the navigation. It is a specific design and should be consistent globally.
2. The pencil banner line height should also be specified here for now. Since it is an global element appears on both old and new page designs. I think to override the old protocol default line-height might needs much more testing before we proceed. For now, we might have to specify line-height for new global components.

I hope this helps answer the question regarding the footer line-height too.

2025-01-09 23:40 UTC, janbrasna commented
Thinking aloud… this should start with redefining --body-line-height:1.4 on protocol-mozilla-2024 to start with, to apply the 1.2 to all the content, old and new?

And then set header nav and footer link lists line height to even smaller value, neither of those used today?

(I'll probably pass on this, as there's a lot of tribal knowledge needed, sounds like neither /about nor /products have the correct nav & footer metrics and should be unified to whole another value afterall… I may draft how that would look in this PR to demonstrate, but not sure that's the expected outcome…)

2025-01-10 13:08 UTC, janbrasna reviewed
BTW I have followed the above posted metrics "literally" in this branch to test out, the biggest impact is perhaps all the pre-refresh pages that got line-height 1.4 at #15144 — and these would change now to 1.2 wholesale.

Another impact is e.g. the submenu that would need further tweaks after the line-height moving out of align with the logo:

> <img width="255" alt="Screenshot 2025-01-10 at 1 11 07" src="https://github.com/user-attachments/assets/2f8c256b-1f84-459a-acc8-2a2270e6ff31" />

Generally there seems to be rules coming from different stages or the refresh, ending up rendering slightly differently on the output. We ran into another interaction between m24-base and protocol-mozilla-2024 today, and it would seem like the duplication/inheritance causes some woes — so maybe only using one or the other separately will be more manageable in the end.

2025-01-10 14:24 UTC, wen-2018 commented
> Thinking aloud… this should start with redefining --body-line-height:1.4 on protocol-mozilla-2024 to start with, to apply the 1.2 to all the content, old and new?

I think the goal is to build a brand new design system like the current protocol but for the new M24 styles evetually. So we might not want to override the default body line for the pages/components using the protocol designs. The line-heights I listed above are for components/pages using the M24 styles. 

In summary:
- New navigation, new footer, new pencil banner or any other new global components, about and home page (new headings) should be using the line-heights listed here https://github.com/mozilla/bedrock/pull/15790#pullrequestreview-2537439357
- Sub menu, any other page having old protocol designs should use the existing default protocol  line-height, for body text, it should be 1.4 now; for headings, it should be 1.1

2025-01-10 14:28 UTC, janbrasna commented
OK, so the other way around how it inherits today — protocol-mozilla-2024 should not override any metrics from the refreshed components older pages may use, esp. nav & footer.

I'll think about that. Thanks for the info.

2025-01-10 14:30 UTC, wen-2018 commented on media/css/m24/base.scss
> -    font-variant-ligatures: none;
I think it's likely font-variant-ligatures was disabled for M24 when the font is still in beta. 

@stephaniehobson Could you confirm this is the case and we could remove them in M24 base styles now?

2025-01-10 17:14 UTC, stephaniehobson commented on media/css/m24/base.scss
> -    font-variant-ligatures: none;
Font ligatures are an accessibility concern. Changing the shape of the letters by combining them introduces problems for some readers. We should keep them disabled in the base styles.

2025-01-10 17:24 UTC, janbrasna commented on media/css/m24/base.scss
> -    font-variant-ligatures: none;
Ah, okay, I thought that a11y override would come from UA styles, if preferred.

I'll try to make that consistent between the old and the new pages then.
Thanks for the info, appreciate it.

2025-05-01 22:17 UTC, closed without merging

2025-05-01 22:17 UTC, janbrasna commented
Resolved in #16156