Add pre-commit hooks configuration and docs
mozilla/bedrock pull request #9162
Opened 2020-07-16 17:17 UTC by pmac

See https://pre-commit.com/ for details

2021-02-03 17:34 UTC, Aayushap1 approved these changes

2021-09-29 09:52 UTC, alexgibson requested changes
@pmac I didn't pull this locally just yet, but if you want to update dependencies I'll take it for a spin?

2021-09-29 09:52 UTC, alexgibson commented on .pre-commit-config.yaml
> +          - "stylelint-config-standard@20.0.0"
I think this can be updated to `13.12.0`

2021-09-29 09:52 UTC, alexgibson commented on .pre-commit-config.yaml
> +          - "eslint@6.3.0"
Update to `7.0.0`

2021-09-29 09:52 UTC, alexgibson commented on .pre-commit-config.yaml
> +          - "eslint-plugin-no-jquery@2.5.0"
This can now be removed

2021-09-29 09:52 UTC, alexgibson commented on setup.cfg
> +    docs,
should we add `assets` here now as well?

2021-09-29 09:52 UTC, alexgibson commented on .pre-commit-config.yaml
> +            docs|
Add `assets|`

2021-09-29 09:53 UTC, alexgibson commented on .pre-commit-config.yaml
> +            docs|
add `assets|`?

2021-09-29 15:39 UTC, pmac commented
Thanks for taking a look and looking into the deps. I'll get it updated.

2021-09-29 15:59 UTC, pmac commented
Updated and ready for another try. Working well for me.

2021-09-29 16:01 UTC, pmac commented
I removed all references to `static*` because we no longer use those folders, right? Or do we still use static for something?

2021-09-29 18:23 UTC, pmac commented
Ah! No, we still do use `static` but not the `static_*` ones. I'll fix.

2021-10-01 10:32 UTC, alexgibson approved these changes
This worked well for me, r+ 💯

2021-10-01 10:33 UTC, merged