Expose /contribute for L10n (Fixes #9151)
mozilla/bedrock pull request #9305
Opened 2020-08-12 09:06 UTC by alexgibson

## Description
- Adds `mozorg/contribute.ftl`
- Converts `/contribute/` page to use Fluent IDs.
- Updates view tests.

## Issue / Bugzilla link
#9151

## Testing
- [ ] Did I miss any strings?
- [ ] Did I miss any brand names?

2020-09-14 18:32 UTC, craigcook requested changes
Just two teeny nits. r+wc 🧈

2020-09-14 18:32 UTC, craigcook commented on bedrock/mozorg/templates/mozorg/contribute/contribute-2020.html
> +            <p class="mzp-c-card-desc">{{ ftl('contribute-task-support-desc') }}.</p>
Stray `.` at the end here.

2020-09-14 18:32 UTC, craigcook commented on l10n/en/mozorg/contribute.ftl
> +contribute-task-support-desc = Help make { -brand-name-mozilla } products easy to use. Answer user’s "help" questions as part of the { -brand-name-mozilla } Support Community forums.
Should probably use curly quotes around `help`

2020-09-15 14:23 UTC, craigcook commented on l10n/en/mozorg/contribute.ftl
> +contribute-task-support-desc = Help make { -brand-name-mozilla } products easy to use. Answer user’s "help" questions as part of the { -brand-name-mozilla } Support Community forums.
Also, I think this should be `users’` to make it plural, though it's one of those weird possessives with the hanging apostrophe. Or we could try `answer people’s “help” questions` if we think `users’` is too clunky.

2020-09-15 15:22 UTC, alexgibson commented
Thanks @craigcook updated

2020-09-15 15:25 UTC, craigcook approved these changes

2020-09-15 15:36 UTC, merged