Hide Firefox Send [fix #9316]
mozilla/bedrock pull request #9326
Opened 2020-08-25 21:58 UTC by craigcook

## Description
Removes promotional references/links to Firefox Send, hiding them temporarily behind the switch `firefox-send-active`. Send is hidden by default when the switch is OFF, so we can quickly switch it ON and unhide Send when/if Send becomes available again (and we'd follow that up with some cleanup to remove the switch and make it permanent again).

## Issue / Bugzilla link
#9316 

## Testing
Note that the switch hides Send when it's OFF and switches are treated as ON in dev mode. You'll need to test locally in prod mode to verify it's hidden.

Send should be removed from:

Main nav
Footer
http://localhost:8000/firefox/
http://localhost:8000/exp/firefox/
http://localhost:8000/firefox/products/
http://localhost:8000/firefox/accounts/
http://localhost:8000/firefox/privacy/
http://localhost:8000/firefox/welcome/3/

2020-09-01 13:20 UTC, alexgibson requested changes
One visual difference spotted between /firefox/accounts/ and /exp/firefox/accounts/, but otherwise this lgtm 👍

2020-09-01 13:20 UTC, alexgibson commented on bedrock/firefox/templates/firefox/accounts.html
> +    <ul class="c-product-list {% if switch('firefox-send-active') %}l-columns-two{% else %}l-columns-three{% endif %}">
Should we also apply this to the /exp/firefox/accounts/ page? (the CSS changes might need updating there too).

2020-09-02 06:31 UTC, craigcook commented
Updated!

2020-09-02 08:09 UTC, alexgibson approved these changes

2020-09-02 08:09 UTC, merged