Copy updates for German sept landing page (#9361)
mozilla/bedrock pull request #9460
Opened 2020-09-29 08:15 UTC by alexgibson

## Description
A couple of minor copy amends for German

## Issue / Bugzilla link
#9361

2020-09-29 22:28 UTC, stephaniehobson requested changes
Copy-pasta or some German punctuation I'm not famillir with...

2020-09-29 22:28 UTC, stephaniehobson commented on bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
> +{% set tw_text = 'Schütze das Web, das du liebst. Unfck the rest.”'|urlencode %}
I don't see the matching open quote of this close quote. 🍝 ?

2020-09-30 09:26 UTC, alexgibson commented
@stephaniehobson thanks updated - I've added in a couple more minor updates since this PR was opened.

2020-09-30 16:18 UTC, amychurchwell commented on bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
> +        link_url='https://blog.mozilla.org/firefox/de/soziale-medien-warum-kostenlos-doch-seinen-preis-hat/',
this URL is not found, is it correct?

2020-09-30 16:19 UTC, alexgibson commented on bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
> +        link_url='https://blog.mozilla.org/firefox/de/soziale-medien-warum-kostenlos-doch-seinen-preis-hat/',
yes it will be live by tomorrow, thanks

2020-09-30 16:20 UTC, amychurchwell approved these changes
lgtm r+

2020-09-30 16:20 UTC, merged