Add exp variant of EN unfck page
mozilla/bedrock pull request #9496
Opened 2020-10-01 22:12 UTC by stephaniehobson

## Description

Add exp variant of EN unfck page.

## Issue / Bugzilla link

#9334 

## Testing

http://localhost:8000/en-US/exp/firefox/unfck/

2020-10-02 08:05 UTC, alexgibson requested changes

2020-10-02 08:05 UTC, alexgibson commented on bedrock/exp/templates/exp/firefox/campaign/unfck/index.html
> + {% extends "firefox/campaign/unfck/index.html" %}
Nit: indentation here and below

2020-10-02 08:05 UTC, alexgibson commented on bedrock/exp/urls.py
> +    page('firefox/unfck', 'exp/firefox/campaign/unfck/index.html', active_locales=['en-US', 'en-GB', 'en-CA']),
The main production page is only enabled for `en-US` - shouldn't both pages match?

2020-10-02 21:41 UTC, stephaniehobson commented
Updated.

2020-10-05 12:37 UTC, alexgibson approved these changes

2020-10-05 12:37 UTC, merged