Migrate /policies/participation/ to fluent. (#9666) [skip l10n]
mozilla/bedrock pull request #9703
Opened 2020-11-17 22:09 UTC by amychurchwell

## Description
Migrates /about/governance/policies/participation/ to fluent.

## Issue / Bugzilla link
#9666 

## Testing
http://localhost:8000/en-US/about/governance/policies/participation/

2020-11-18 23:23 UTC, amychurchwell commented
@alexgibson would you be able to take a look at this for me? I keep getting errors locally and I am not sure where the problem is. I have ran `make clean build` and have also started over with the same results.

2020-11-19 09:12 UTC, alexgibson requested changes
Looks like the issue is because of a few missing variables than need passing to thir related strings. The changes below seem to fix things for me.

2020-11-19 09:12 UTC, alexgibson commented on bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
> +    <li>{{ ftl('participation-questions-cpg-questionsmozillacom')|format('mailto:cpg-questions@mozilla.com') }}</li>
```suggestion
    <li>{{ ftl('participation-questions-cpg-questionsmozillacom', url='mailto:cpg-questions@mozilla.com') }}</li>
```

2020-11-19 09:12 UTC, alexgibson commented on bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
> +  <p id="note-1">{{ ftl('participation-1-the-anti-harassment')|format('https://mana.mozilla.org/wiki/display/PR/Open+Door+Policy') }}</p>
```suggestion
  <p id="note-1">{{ ftl('participation-1-the-anti-harassment', url='https://mana.mozilla.org/wiki/display/PR/Open+Door+Policy') }}</p>
```

2020-11-19 09:12 UTC, alexgibson commented on l10n/en/mozorg/about/governance/policies/participation.ftl
> +participation-questions-cpg-questionsmozillacom = Questions: <a href="{ $missing-var }">cpg-questions@mozilla.com</a>
```suggestion
participation-additional-resources = Additional Resources: <a href="{ $url }">How to Report</a>
participation-questions-cpg-questionsmozillacom = Questions: <a href="{ $url }">cpg-questions@mozilla.com</a>
```

2020-11-19 09:12 UTC, alexgibson commented on l10n/en/mozorg/about/governance/policies/participation.ftl
> +participation-1-the-anti-harassment = [1] The anti-harassment policy is accessible to paid staff <a href="{ $missing-var }">here</a>.
```suggestion
participation-1-the-anti-harassment = [1] The anti-harassment policy is accessible to paid staff <a href="{ $url }">here</a>.
```

2020-11-19 19:18 UTC, amychurchwell commented
migration for the existing translations in progress. en is in review.

2020-12-02 00:53 UTC, amychurchwell commented
migrations have merged! https://github.com/mozilla-l10n/www-l10n/pull/138

2020-12-02 14:20 UTC, alexgibson requested changes
Spotted one missing variable, but otherwise this looks good to me?

Do we need to specify a config for these Fluent files? As it stands this would go out to all locales.

2020-12-02 14:20 UTC, alexgibson commented on bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
> +    <li>{{ ftl('participation-additional-resources', url('mozorg.about.governance.policies.reporting')) }}</li>
```suggestion
    <li>{{ ftl('participation-additional-resources', url=url('mozorg.about.governance.policies.reporting')) }}</li>
```

2020-12-02 14:20 UTC, alexgibson commented on bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
> +           changelog='https://github.com/mozilla/cpg/blob/master/CHANGELOG.md') }}
Nit: indentation

2020-12-02 14:20 UTC, alexgibson commented on bedrock/mozorg/urls.py
> +         ftl_files=['mozorg/about/governance/policies/participation.ftl']),
Nit: think you can omit the `.ftl` extension here?

2020-12-02 14:24 UTC, alexgibson commented
Ok, I saw you added the Fluent config in https://github.com/mozilla/bedrock/pull/9708

Once you rebase / update this PR then I think this should be good to merge as well :)

2020-12-02 16:36 UTC, alexgibson approved these changes
🍡

2020-12-02 16:45 UTC, merged