[fix #9719] Set up whatsnew page for Firefox 84.0
mozilla/bedrock pull request #9720
Opened 2020-11-20 18:11 UTC by craigcook

## Description
Updates the whatsnew view to reuse the WNP82 template for Firefox 84.0. There are no other changes, we're just rerunning the exact same page.

However, if we really want to keep each WNP separate and self-contained we could duplicate and rename the 82 template and assets. Reusing them in place means we wouldn't be able to delete them until 84 also cycles out. It incurs a small technical debt and hence the comment to remind future devs, but it also feels kinda silly making exact duplicates just so we can more easily delete some later. If that's the better way I can be persuaded.

## Issue / Bugzilla link
#9719 

## Testing
http://localhost:8000/en-US/firefox/84.0/whatsnew/

It's English only; other locales should fall back to the evergreen page.

2020-11-20 20:46 UTC, craigcook commented
We need different UTM params for 84 (but of course, I hadn't thought of that) so while there may be other options I think I'm just going to duplicate the template after all.

2020-11-30 09:46 UTC, alexgibson requested changes
Spotted a utm param that looks like it still needs updating, and also a missing JS bundle. But otherwise this all looks as expected 👍 

I'm a little lost as to why we're duplicating the templates here in order to provide different utm params. We added a way to standardize utms params on /whatsnew pages, so they are automatically available in the template via a [context variable](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L624-L625). The hope was that this would avoid the need for template duplication like this.

Is there something that's not working there, or that we could improve to help need doing this? (not a blocker for this PR).

2020-11-30 09:46 UTC, alexgibson commented on bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx84.html
> +        <a href="https://vpn.mozilla.org/?utm_source=mozilla.org-whatsnew82&utm_medium=referral&utm_campaign=whatsnew84&entrypoint=mozilla.org-whatsnew84" class="mzp-c-button mzp-t-product mzp-t-lg"
```suggestion
        <a href="https://vpn.mozilla.org/?utm_source=mozilla.org-whatsnew84&utm_medium=referral&utm_campaign=whatsnew84&entrypoint=mozilla.org-whatsnew84" class="mzp-c-button mzp-t-product mzp-t-lg" rel="external" data-cta-text="Get Mozilla VPN Now" data-cta-type="button">Get Mozilla VPN Now</a>
```

2020-11-30 09:46 UTC, alexgibson commented on bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx84.html
> +  {{ js_bundle('firefox_whatsnew_84') }}
This bundle doesn't seem to exist, does it need duplicating?

2020-11-30 15:18 UTC, craigcook commented
D'oh, I'd forgotten about the variable. Though there may still be some tiny advantage to duping the template so it's independent of the 82 template... but the repetition might be more debt than the reuse?

2020-11-30 16:25 UTC, alexgibson approved these changes

2020-11-30 16:25 UTC, merged