Update to Protocol 13.0.0 [fix #8876]
mozilla/bedrock pull request #9744
Opened 2020-12-02 23:37 UTC by craigcook

## Description
This is a big update that implements brand themes. It ended up touching a lot of pages to make minor style tweaks, mainly adjusting some font sizes because the type scale has been changed and declaring explicit colors for headings where needed, plus some general cleanup here and there (code formatting, switching to tokens, etc).

## Issue / Bugzilla link
#8876 

## Testing

2020-12-03 17:22 UTC, craigcook commented on bedrock/mozorg/templates/mozorg/home/home-de.html
> +        title='Für Dich & das Internet. <br>Schon seit 1998.'|safe,
This is just a fix for a bug I spotted, unrelated to this PR (the `<br>` was rendered as text, not sure how long this bug has been in production).

2020-12-03 17:38 UTC, craigcook commented on media/css/firefox/browsers-products.scss
> +    a:link,
The `light-links` mixin changed so inverted links now have color, but here and in a few other spots they need to be explicitly white. I've filed https://github.com/mozilla/protocol/issues/648

2020-12-08 00:27 UTC, craigcook commented
I think this is ready for review. Although the bit that updates Protocol is itself very small, this turned into a visual check of pretty much every page I could find and making a few adjustments where they seemed necessary.

2020-12-11 10:23 UTC, alexgibson commented
I spotted some pages where minor issues with light links occur (or at least link colors have changed compared to prod)

http://localhost:8000/en-US/firefox/windows/

![image](https://user-images.githubusercontent.com/400117/101892006-b9044800-3b9a-11eb-82fe-293590472075.png)

http://localhost:8000/ru/firefox/new/

![image](https://user-images.githubusercontent.com/400117/101892053-cb7e8180-3b9a-11eb-80ee-dd025bade856.png)

http://localhost:8000/en-US/firefox/79.0/whatsnew/all/

![image](https://user-images.githubusercontent.com/400117/101892103-de915180-3b9a-11eb-97b3-63d9070e83f4.png)

(The release notes link color is also on other whatsnew pages)

2020-12-11 10:24 UTC, alexgibson commented
I pushed this branch for a test run and all seems well: https://gitlab.com/mozmeao/www-config/-/pipelines/228406086

2020-12-11 10:28 UTC, alexgibson requested changes
I went through the migration tips and things look good too: https://github.com/mozilla/protocol/releases/tag/v13.0.0

r+wc on the small changes. I'm sure there are likely some other areas where we'll have light link issues on dark backgrounds but those seem minor and can easily be fixed.

2020-12-11 14:58 UTC, craigcook commented
The dark theme link colors were specified in https://github.com/mozilla/protocol/issues/428 though the values there strayed from the tokens and I ended up picking the token that was closest. But now seeing them in practice I still think the link colors are all too dark and/or saturated on dark backgrounds. That blue on an ink background is a real shock to the retinas.

So I'd like to revise the inverse link colors in the theme and publish a 13.0.1, which can also include the new `white-links` mixin for https://github.com/mozilla/protocol/issues/648 (I've already got it ready, just haven't submitted a PR yet). That will mean letting this PR sit just a little longer, but that's probably better than doing a bunch of overrides in bedrock that we'd just have to remove later.

2020-12-17 09:07 UTC, alexgibson approved these changes
Updates look good to me. From a user perspective, I still find things like this a bit confusing:

![image](https://user-images.githubusercontent.com/400117/102466469-f9eed780-4046-11eb-9f5d-0f12179375a3.png)

Looking a little deeper, I think it's because the top link is actually a `<button>`, but styled to look like a link. This is really another UX / design problem altogether imho, so not a blocker. But if you want to update the button color to match the new link styles then I'll leave that up to you. r+! 🕶️

2020-12-17 15:35 UTC, craigcook commented
Maybe we should just go with white links on those pages anyway... I'll do that.

2020-12-17 15:49 UTC, merged