features/translate
mozilla/bedrock pull request #9771
Opened 2020-12-08 23:13 UTC by stephaniehobson

## Description

## Issue / Bugzilla link

## Testing

2020-12-16 21:53 UTC, craigcook requested changes
Looks good, just some images missing `alt` attributes.

2020-12-16 21:53 UTC, craigcook commented on bedrock/firefox/templates/firefox/features/translate.html
> +    <img src="{{ static('img/firefox/features/translate/translation.png') }}">
Missing `alt` here, too.

2020-12-17 00:47 UTC, stephaniehobson commented
Updated!

2020-12-17 00:59 UTC, craigcook approved these changes
🔒

2020-12-17 00:59 UTC, merged