Add WNP 85 for /de/ (Fixes #9856)
mozilla/bedrock pull request #9857
Opened 2021-01-21 14:25 UTC by alexgibson

## Description

http://localhost:8000/de/firefox/85.0/whatsnew/all/

## Issue / Bugzilla link
#9856

## Testing
TODO

2021-01-21 16:06 UTC, alexgibson commented
This is ready for code review, and needs to be live on Monday 25th ready for the 85 launch the next day.

Marking as do-not-merge for now whilst legal takes a look at the copy.

2021-01-21 16:35 UTC, maxxcrawford requested changes
Requesting one change (low-res image issue) but looks good otherwise! 

I am calling out an additional issue, but it may be out of scope for this PR: The error text is in english when trying to submit the Send to Device form. Is this something that can be fixed here? If not, I can file a seperate bug. 

<img width="570" alt="image" src="https://user-images.githubusercontent.com/2692333/105381038-2eb8f600-5bd4-11eb-8567-9f020a63284a.png">

2021-01-21 16:35 UTC, maxxcrawford commented on bedrock/firefox/templates/firefox/whatsnew/whatsnew-mobile-de.html
> +    <img class="wnp-main-image" src="{{ static('protocol/img/logos/firefox/browser/logo-md.png') }}" alt="">
Reviewing the rendered HTML, I'm not getting the [high-res version](https://github.com/mozilla/protocol-assets/blob/main/logos/firefox/logo-md-high-res.png) of the hero logo. Is it missing a `data-high-res="true"` attribute? 

An alternative would be to to use [the SVG version](https://github.com/mozilla/protocol-assets/blob/main/logos/firefox/logo.svg), and make sure the `.wnp-main-image` class has a max-width.

2021-01-21 16:46 UTC, alexgibson commented
> I am calling out an additional issue, but it may be out of scope for this PR: The error text is in english when trying to submit the Send to Device form. Is this something that can be fixed here? If not, I can file a seperate bug.

The tooltip is a browser feature, not part of the web page itself, so the language depends on your browser settings.

2021-01-21 16:50 UTC, alexgibson commented
@maxxcrawford thanks for the review, updated with the high res image.

2021-01-21 17:30 UTC, maxxcrawford approved these changes
LGTM! 🚀

2021-01-21 17:31 UTC, maxxcrawford commented
@alexgibson Added the ⚠️ DNM label, just in case.

2021-01-25 08:59 UTC, alexgibson commented
Got the green light to merge / push this.

2021-01-25 08:59 UTC, merged