Remove legacy /contribute page (Fixes #9819)
mozilla/bedrock pull request #9921
Opened 2021-02-11 13:23 UTC by alexgibson

## Description
http://localhost:8000/en-US/contribute/

## Issue / Bugzilla link
#9819

## Testing
- [ ] Did I miss any stray assets?

2021-02-22 20:52 UTC, maxxcrawford requested changes
I caught what a few artifacts: 
- A reference to the `contribute-2020` naming within the [`bedrock/mozorg/views.py`](https://github.com/alexgibson/bedrock/blob/contribute-lang/bedrock/mozorg/views.py#L142-L153) file. Does this file need to be updated? 
- Flagging the removed SVGs that are still referenced in the SCSS file, and erroring out in the console. Should these SVGs be added back?

2021-02-22 20:52 UTC, maxxcrawford commented on media/img/contribute/icon/cal.svg
> -<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
This file (and the other three icon SVGs) is still in use on the [`media/css/mozorg/contribute.scss`](https://github.com/alexgibson/bedrock/blob/contribute-lang/media/css/mozorg/contribute.scss#L379-L393) file. These SVG icons being removed are showing as 404'ing in the console: 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/2692333/108766346-a7d0a380-751a-11eb-90f1-f02bdc308626.png">

2021-02-23 09:03 UTC, alexgibson commented
@maxxcrawford nice catch! Removed the unused view and restored the icons 👍

2021-02-24 17:14 UTC, maxxcrawford approved these changes

2021-02-24 17:15 UTC, merged